<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>23&nbsp; Chapter 19: Analysis of Variance II — Applications and Randomized Block Designs – MATH 5010: Foundations of Statistical Theory &amp; Probability</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/chapter-20-bayesian-inference.html" rel="next">
<link href="../chapters/chapter-18-anova1.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-53391ae0d416d99de149949e142ad115.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-24dd7dc8f02457b0d1995d224439a69a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-53391ae0d416d99de149949e142ad115.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../assets/styles.css">
</head>

<body class="nav-sidebar docked quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/chapter-19-anova2-applications.html"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Chapter 19: Analysis of Variance II — Applications and Randomized Block Designs</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">MATH 5010: Foundations of Statistical Theory &amp; Probability</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/wanghemath/Book-ProbabilityStatisticalTheory" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">MATH 5010</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../labs-summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Computer Labs and Interactive Pages</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-01-basic-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Chapter 1: Basic Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-02-random-variables-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Chapter 2: Random Variables and Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-03-joint-conditional-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chapter 3: Joint and Conditional Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-04-expectations-moments-mgf.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Chapter 4: Expectations, Moments, and Moment Generating Functions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-05-transformations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Chapter 5: Transformations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-06-conditional-expectations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Chapter 6: Conditional Expectations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-06-extra-multinomial-multinormal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Chapter 6 Extra: Multinomial and Multinormal Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-07-inequalities-identities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Chapter 7: Inequalities and Identities</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-08-sampling-order-statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Chapter 8: Sampling and Order Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-09-convergence-theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Chapter 9: Convergence Theory and Limit Theorems</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-10-monte-carlo-sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Chapter 10: Monte Carlo Sampling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-11-sufficient-statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Chapter 11: Sufficient Statistics and the Likelihood Principle</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-12-point-estimation1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Chapter 12: Point Estimation I — Finding Estimators</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-13-point-estimation2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Chapter 13: Point Estimation II — Evaluating Estimators</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-14-hypothesis-tests1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Chapter 14: Hypothesis Tests I — Methods of Finding Tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-15-hypothesis-tests2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Chapter 15: Hypothesis Tests II — Evaluating Tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-16-interval-estimation1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Chapter 16: Interval Estimation I — Finding Interval Estimators</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-17-interval-estimation2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Chapter 17: Interval Estimation II — Evaluating Interval Estimators</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-18-anova1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Chapter 18: Analysis of Variance I — One-Way ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-19-anova2-applications.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Chapter 19: Analysis of Variance II — Applications and Randomized Block Designs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapter-20-bayesian-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Chapter 20: Bayesian Inference</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#analysis-of-variance-ii-applications-and-randomized-block-designs" id="toc-analysis-of-variance-ii-applications-and-randomized-block-designs" class="nav-link active" data-scroll-target="#analysis-of-variance-ii-applications-and-randomized-block-designs"><span class="header-section-number">24</span> Analysis of Variance II: Applications and Randomized Block Designs</a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview"><span class="header-section-number">25</span> Overview</a></li>
  <li><a href="#review-and-summary-of-one-way-anova" id="toc-review-and-summary-of-one-way-anova" class="nav-link" data-scroll-target="#review-and-summary-of-one-way-anova"><span class="header-section-number">26</span> Review and Summary of One-Way ANOVA</a>
  <ul class="collapse">
  <li><a href="#background" id="toc-background" class="nav-link" data-scroll-target="#background"><span class="header-section-number">26.1</span> Background</a></li>
  <li><a href="#one-way-anova-model" id="toc-one-way-anova-model" class="nav-link" data-scroll-target="#one-way-anova-model"><span class="header-section-number">26.2</span> One-Way ANOVA Model</a></li>
  <li><a href="#classical-anova-hypothesis" id="toc-classical-anova-hypothesis" class="nav-link" data-scroll-target="#classical-anova-hypothesis"><span class="header-section-number">26.3</span> Classical ANOVA Hypothesis</a></li>
  <li><a href="#dot-notation-and-means" id="toc-dot-notation-and-means" class="nav-link" data-scroll-target="#dot-notation-and-means"><span class="header-section-number">26.4</span> Dot Notation and Means</a></li>
  <li><a href="#partitioning-sums-of-squares" id="toc-partitioning-sums-of-squares" class="nav-link" data-scroll-target="#partitioning-sums-of-squares"><span class="header-section-number">26.5</span> Partitioning Sums of Squares</a></li>
  <li><a href="#mean-squares-and-the-f-statistic" id="toc-mean-squares-and-the-f-statistic" class="nav-link" data-scroll-target="#mean-squares-and-the-f-statistic"><span class="header-section-number">26.6</span> Mean Squares and the F Statistic</a></li>
  <li><a href="#the-one-way-anova-table" id="toc-the-one-way-anova-table" class="nav-link" data-scroll-target="#the-one-way-anova-table"><span class="header-section-number">26.7</span> The One-Way ANOVA Table</a></li>
  </ul></li>
  <li><a href="#example-comparing-three-golf-ball-brands" id="toc-example-comparing-three-golf-ball-brands" class="nav-link" data-scroll-target="#example-comparing-three-golf-ball-brands"><span class="header-section-number">27</span> Example: Comparing Three Golf Ball Brands</a></li>
  <li><a href="#example-smoking-and-heart-rate" id="toc-example-smoking-and-heart-rate" class="nav-link" data-scroll-target="#example-smoking-and-heart-rate"><span class="header-section-number">28</span> Example: Smoking and Heart Rate</a></li>
  <li><a href="#applications-and-interpretation" id="toc-applications-and-interpretation" class="nav-link" data-scroll-target="#applications-and-interpretation"><span class="header-section-number">29</span> Applications and Interpretation</a>
  <ul class="collapse">
  <li><a href="#what-anova-tells-us" id="toc-what-anova-tells-us" class="nav-link" data-scroll-target="#what-anova-tells-us"><span class="header-section-number">29.1</span> What ANOVA tells us</a></li>
  <li><a href="#why-not-just-run-many-t-tests" id="toc-why-not-just-run-many-t-tests" class="nav-link" data-scroll-target="#why-not-just-run-many-t-tests"><span class="header-section-number">29.2</span> Why not just run many t-tests?</a></li>
  <li><a href="#follow-up-analysis-after-anova" id="toc-follow-up-analysis-after-anova" class="nav-link" data-scroll-target="#follow-up-analysis-after-anova"><span class="header-section-number">29.3</span> Follow-up analysis after ANOVA</a></li>
  </ul></li>
  <li><a href="#design-of-experiments" id="toc-design-of-experiments" class="nav-link" data-scroll-target="#design-of-experiments"><span class="header-section-number">30</span> Design of Experiments</a></li>
  <li><a href="#randomized-block-designs" id="toc-randomized-block-designs" class="nav-link" data-scroll-target="#randomized-block-designs"><span class="header-section-number">31</span> Randomized Block Designs</a>
  <ul class="collapse">
  <li><a href="#motivation" id="toc-motivation" class="nav-link" data-scroll-target="#motivation"><span class="header-section-number">31.1</span> Motivation</a></li>
  <li><a href="#when-to-use-a-randomized-block-design" id="toc-when-to-use-a-randomized-block-design" class="nav-link" data-scroll-target="#when-to-use-a-randomized-block-design"><span class="header-section-number">31.2</span> When to Use a Randomized Block Design</a></li>
  <li><a href="#structure-of-a-randomized-block-design" id="toc-structure-of-a-randomized-block-design" class="nav-link" data-scroll-target="#structure-of-a-randomized-block-design"><span class="header-section-number">31.3</span> Structure of a Randomized Block Design</a></li>
  <li><a href="#hypotheses-for-treatments" id="toc-hypotheses-for-treatments" class="nav-link" data-scroll-target="#hypotheses-for-treatments"><span class="header-section-number">31.4</span> Hypotheses for Treatments</a></li>
  </ul></li>
  <li><a href="#computing-sums-of-squares-in-a-randomized-block-design" id="toc-computing-sums-of-squares-in-a-randomized-block-design" class="nav-link" data-scroll-target="#computing-sums-of-squares-in-a-randomized-block-design"><span class="header-section-number">32</span> Computing Sums of Squares in a Randomized Block Design</a>
  <ul class="collapse">
  <li><a href="#anova-table-for-randomized-block-design" id="toc-anova-table-for-randomized-block-design" class="nav-link" data-scroll-target="#anova-table-for-randomized-block-design"><span class="header-section-number">32.1</span> ANOVA Table for Randomized Block Design</a></li>
  </ul></li>
  <li><a href="#example-complete-randomized-block-design-computation" id="toc-example-complete-randomized-block-design-computation" class="nav-link" data-scroll-target="#example-complete-randomized-block-design-computation"><span class="header-section-number">33</span> Example: Complete Randomized Block Design Computation</a></li>
  <li><a href="#lab-randomized-block-designs-with-python" id="toc-lab-randomized-block-designs-with-python" class="nav-link" data-scroll-target="#lab-randomized-block-designs-with-python"><span class="header-section-number">34</span> Lab: Randomized Block Designs with Python</a></li>
  <li><a href="#practice-problems" id="toc-practice-problems" class="nav-link" data-scroll-target="#practice-problems"><span class="header-section-number">35</span> Practice Problems</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">36</span> Summary</a>
  <ul class="collapse">
  <li><a href="#references-and-further-reading" id="toc-references-and-further-reading" class="nav-link" data-scroll-target="#references-and-further-reading"><span class="header-section-number">36.1</span> References and Further Reading</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/wanghemath/Book-ProbabilityStatisticalTheory/edit/main/chapters/chapter-19-anova2-applications.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/wanghemath/Book-ProbabilityStatisticalTheory/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Chapter 19: Analysis of Variance II — Applications and Randomized Block Designs</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="analysis-of-variance-ii-applications-and-randomized-block-designs" class="level1" data-number="24">
<h1 data-number="24"><span class="header-section-number">24</span> Analysis of Variance II: Applications and Randomized Block Designs</h1>
<p>This chapter continues ANOVA by emphasizing <strong>applications, interpretation, experimental design, and randomized block designs</strong>. We review the one-way ANOVA table, work through complete numerical examples, discuss why multiple pairwise tests can inflate Type I error, and introduce blocking as a way to remove nuisance variation from the error term.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Topics">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Topics
</div>
</div>
<div class="callout-body-container callout-body">
<p>One-way ANOVA review; complete ANOVA computations; ANOVA interpretation; multiple testing; follow-up comparisons; principles of experimental design; control, randomization, replication, and blocking; randomized block design model; RBD sums of squares; RBD ANOVA table; treatment and block effects.</p>
</div>
</div>
</section>
<section id="overview" class="level1" data-number="25">
<h1 data-number="25"><span class="header-section-number">25</span> Overview</h1>
<p>This section shows how ANOVA is used in real data analysis and how experimental design affects the interpretation of ANOVA results.</p>
<p>The main topics are:</p>
<ol type="1">
<li><p>review and summary of one-way ANOVA;</p></li>
<li><p>complete numerical ANOVA computations;</p></li>
<li><p>applications and interpretation;</p></li>
<li><p>principles of experimental design;</p></li>
<li><p>randomized block designs.</p></li>
</ol>
</section>
<section id="review-and-summary-of-one-way-anova" class="level1" data-number="26">
<h1 data-number="26"><span class="header-section-number">26</span> Review and Summary of One-Way ANOVA</h1>
<p>This section reviews the one-way ANOVA model and the classical ANOVA table before moving to applications.</p>
<section id="background" class="level2" data-number="26.1">
<h2 data-number="26.1" class="anchored" data-anchor-id="background"><span class="header-section-number">26.1</span> Background</h2>
<p>One-way ANOVA is used when we want to compare the means of several populations or treatment groups.</p>
<p>ANOVA is appropriate in two common settings:</p>
<ol type="1">
<li><p><span class="math inline">\(k\)</span> independent random samples are drawn from <span class="math inline">\(k\)</span> populations;</p></li>
<li><p><span class="math inline">\(k\)</span> different treatments are applied to a homogeneous group of experimental units, which is subdivided into <span class="math inline">\(k\)</span> subgroups.</p></li>
</ol>
<p>The scientific question is: <span class="math display">\[\text{Do the treatment groups have the same population mean, or does at least one treatment differ?}\]</span></p>
</section>
<section id="one-way-anova-model" class="level2" data-number="26.2">
<h2 data-number="26.2" class="anchored" data-anchor-id="one-way-anova-model"><span class="header-section-number">26.2</span> One-Way ANOVA Model</h2>
<p>The one-way ANOVA model represents each observation as a group mean plus random error.</p>
<p>Let <span class="math inline">\(X_{ij}\)</span> be the <span class="math inline">\(j\)</span>th observation in group <span class="math inline">\(i\)</span>, where <span class="math display">\[i=1,\ldots,k, \qquad j=1,\ldots,n_i.\]</span> The model is <span class="math display">\[X_{ij}=\mu_i+\epsilon_{ij},\]</span> where <span class="math inline">\(\mu_i\)</span> is the mean of group <span class="math inline">\(i\)</span> and <span class="math inline">\(\epsilon_{ij}\)</span> is the random error.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Definition 1</strong> (One-way ANOVA assumptions). The classical one-way ANOVA model assumes:</p>
<ol type="1">
<li><p>the samples are independently selected from the <span class="math inline">\(k\)</span> populations;</p></li>
<li><p>the <span class="math inline">\(k\)</span> populations are approximately normal;</p></li>
<li><p>all <span class="math inline">\(k\)</span> population variances are equal;</p></li>
<li><p>equivalently, <span class="math display">\[\epsilon_{ij}\overset{\text{iid}}{\sim} \operatorname{Normal}(0,\sigma^2).\]</span></p></li>
</ol>
</div>
</div>
</section>
<section id="classical-anova-hypothesis" class="level2" data-number="26.3">
<h2 data-number="26.3" class="anchored" data-anchor-id="classical-anova-hypothesis"><span class="header-section-number">26.3</span> Classical ANOVA Hypothesis</h2>
<p>The classical ANOVA test asks whether all treatment means are equal.</p>
<p>The hypotheses are <span class="math display">\[H_0: \mu_1=\mu_2=\cdots=\mu_k\]</span> versus <span class="math display">\[H_1: \mu_i\neq \mu_j \quad \text{for some } i,j.\]</span></p>
<p>Rejecting <span class="math inline">\(H_0\)</span> means that at least one group mean differs from another. It does not immediately tell us which means differ. Follow-up comparisons, contrasts, or multiple-comparison procedures are needed for that question.</p>
</section>
<section id="dot-notation-and-means" class="level2" data-number="26.4">
<h2 data-number="26.4" class="anchored" data-anchor-id="dot-notation-and-means"><span class="header-section-number">26.4</span> Dot Notation and Means</h2>
<p>Dot notation provides a compact way to write group totals, group means, and the grand mean.</p>
<p>Let <span class="math display">\[T_{i\cdot}=\sum_{j=1}^{n_i}Y_{ij}\]</span> be the total for group <span class="math inline">\(i\)</span>. Then the group mean is <span class="math display">\[\overline{Y}_{i\cdot}=\frac{T_{i\cdot}}{n_i}=\frac{1}{n_i}\sum_{j=1}^{n_i}Y_{ij}.\]</span> The total sample size is <span class="math display">\[N=\sum_{i=1}^k n_i.\]</span> The grand total is <span class="math display">\[T_{\cdot\cdot}=\sum_{i=1}^{k}\sum_{j=1}^{n_i}Y_{ij}=\sum_{i=1}^k T_{i\cdot},\]</span> and the grand mean is <span class="math display">\[\overline{Y}_{\cdot\cdot}=\frac{1}{N}\sum_{i=1}^{k}\sum_{j=1}^{n_i}Y_{ij}
    =\frac{1}{N}\sum_{i=1}^{k}T_{i\cdot}
    =\frac{1}{N}\sum_{i=1}^{k}n_i\overline{Y}_{i\cdot}.\]</span></p>
</section>
<section id="partitioning-sums-of-squares" class="level2" data-number="26.5">
<h2 data-number="26.5" class="anchored" data-anchor-id="partitioning-sums-of-squares"><span class="header-section-number">26.5</span> Partitioning Sums of Squares</h2>
<p>The key idea of ANOVA is to split total variation into between-group variation and within-group variation.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Definition 2</strong> (Sums of squares). The total sum of squares is <span class="math display">\[\mathrm{SST}_{\mathrm{total}}=\sum_{i=1}^k\sum_{j=1}^{n_i}(Y_{ij}-\overline{Y}_{\cdot\cdot})^2.\]</span> The between-group sum of squares is <span class="math display">\[\mathrm{SSB}_{\mathrm{between}}=\sum_{i=1}^k n_i(\overline{Y}_{i\cdot}-\overline{Y}_{\cdot\cdot})^2.\]</span> The within-group or error sum of squares is <span class="math display">\[\mathrm{SSE}_{\mathrm{error}}=\sum_{i=1}^k\sum_{j=1}^{n_i}(Y_{ij}-\overline{Y}_{i\cdot})^2.\]</span> The fundamental decomposition is <span class="math display">\[\mathrm{SST}_{\mathrm{total}}=\mathrm{SSB}_{\mathrm{between}}+\mathrm{SSE}_{\mathrm{error}}.\]</span></p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Key idea">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Key idea
</div>
</div>
<div class="callout-body-container callout-body">
<p>Interpretation of the decomposition The between-group sum of squares measures how far the group means are from the grand mean. The within-group sum of squares measures random variation around each group mean. If the between-group variation is large compared with the within-group variation, this provides evidence that the treatment means are not all equal.</p>
</div>
</div>
</section>
<section id="mean-squares-and-the-f-statistic" class="level2" data-number="26.6">
<h2 data-number="26.6" class="anchored" data-anchor-id="mean-squares-and-the-f-statistic"><span class="header-section-number">26.6</span> Mean Squares and the F Statistic</h2>
<p>The F statistic compares average between-group variation to average within-group variation.</p>
<p>Define the mean treatment sum of squares and mean error sum of squares by <span class="math display">\[\mathrm{MSB}=\frac{\mathrm{SSB}}{k-1}, \qquad \mathrm{MSE}=\frac{\mathrm{SSE}}{N-k}.\]</span> Under the ANOVA assumptions, <span class="math display">\[\frac{\mathrm{SSE}}{\sigma^2}\sim \chi^2_{N-k}.\]</span> If <span class="math inline">\(H_0: \mu_1=\cdots=\mu_k\)</span> is true, then <span class="math display">\[\frac{\mathrm{SSB}}{\sigma^2}\sim \chi^2_{k-1}.\]</span> Therefore, under <span class="math inline">\(H_0\)</span>, <span class="math display">\[F=\frac{\mathrm{MSB}}{\mathrm{MSE}}
    =\frac{\mathrm{SSB}/(k-1)}{\mathrm{SSE}/(N-k)}
    \sim F_{k-1,N-k}.\]</span> Large values of <span class="math inline">\(F\)</span> provide evidence against <span class="math inline">\(H_0\)</span>.</p>
</section>
<section id="the-one-way-anova-table" class="level2" data-number="26.7">
<h2 data-number="26.7" class="anchored" data-anchor-id="the-one-way-anova-table"><span class="header-section-number">26.7</span> The One-Way ANOVA Table</h2>
<p>The ANOVA table organizes the decomposition of variation and the F-test.</p>
<div class="center">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Source of Variation</th>
<th style="text-align: center;">Sum of Squares</th>
<th style="text-align: center;">df</th>
<th style="text-align: center;">Mean Square</th>
<th style="text-align: center;">F Statistic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Between groups</td>
<td style="text-align: center;"><span class="math inline">\(\mathrm{SSB}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(k-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathrm{MSB}=\mathrm{SSB}/(k-1)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(F_{\mathrm{obs}}=\mathrm{MSB}/\mathrm{MSE}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Within groups</td>
<td style="text-align: center;"><span class="math inline">\(\mathrm{SSE}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(N-k\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathrm{MSE}=\mathrm{SSE}/(N-k)\)</span></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: center;"><span class="math inline">\(\mathrm{SST}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(N-1\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</div>
<p>The p-value is <span class="math display">\[p\text{-value}=\mathbb{P}\left(F_{k-1,N-k}&gt;F_{\mathrm{obs}}\right).\]</span></p>
</section>
</section>
<section id="example-comparing-three-golf-ball-brands" class="level1" data-number="27">
<h1 data-number="27"><span class="header-section-number">27</span> Example: Comparing Three Golf Ball Brands</h1>
<p>This section gives a complete one-way ANOVA computation for comparing three treatment means.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Example 3</strong> (Golf ball distance by brand). A test was conducted to compare the mean distance, in yards, traveled by three brands of golf balls hit by a robotic golfer.</p>
<div class="center">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Brand A</th>
<th style="text-align: center;">Brand B</th>
<th style="text-align: center;">Brand C</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">251.2</td>
<td style="text-align: center;">263.2</td>
<td style="text-align: center;">269.7</td>
</tr>
<tr class="even">
<td style="text-align: center;">245.1</td>
<td style="text-align: center;">262.9</td>
<td style="text-align: center;">263.2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">248.0</td>
<td style="text-align: center;">265.0</td>
<td style="text-align: center;">277.5</td>
</tr>
<tr class="even">
<td style="text-align: center;">251.1</td>
<td style="text-align: center;">254.5</td>
<td style="text-align: center;">267.4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">260.5</td>
<td style="text-align: center;">264.3</td>
<td style="text-align: center;">270.5</td>
</tr>
</tbody>
</table>
</div>
<p>Test whether the mean distances for the three brands are equal.</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Solution
</div>
</div>
<div class="callout-body-container callout-body">
<p>There are <span class="math inline">\(k=3\)</span> groups with <span class="math inline">\(n_1=n_2=n_3=5\)</span>, so <span class="math inline">\(N=15\)</span>. The sample summaries are: <span class="math display">\[\begin{array}{c|ccc}
\text{Brand} &amp; \bar{x}_i &amp; s_i^2 &amp; n_i \\
\hline
A &amp; 251.18 &amp; 33.487 &amp; 5 \\
B &amp; 261.985 &amp; 18.197 &amp; 5 \\
C &amp; 269.66 &amp; 27.253 &amp; 5
\end{array}\]</span> The grand mean is <span class="math display">\[\bar{x}_{\cdot\cdot}
    =\frac{5(251.18)+5(261.985)+5(269.66)}{15}
    \approx 260.94.\]</span> The between-group sum of squares is <span class="math display">\[\begin{aligned}
\mathrm{SSB}
&amp;=\sum_{i=1}^3 n_i(\bar{x}_i-\bar{x}_{\cdot\cdot})^2 \\
&amp;=5(251.18-260.94)^2+5(261.985-260.94)^2+5(269.66-260.94)^2 \\
&amp;\approx 861.89.
\end{aligned}\]</span> The within-group sum of squares is <span class="math display">\[\mathrm{SSE}=\sum_{i=1}^3(n_i-1)s_i^2
    =4(33.487+18.197+27.253)
    \approx 315.75.\]</span> The total sum of squares is <span class="math display">\[\mathrm{SST}=\mathrm{SSB}+\mathrm{SSE}\approx 861.89+315.75=1177.64.\]</span> The ANOVA table is: <span class="math display">\[\begin{array}{lccccc}
\hline
\text{Source} &amp; \text{SS} &amp; \text{df} &amp; \text{MS} &amp; F &amp; p\text{-value} \\
\hline
\text{Treatment} &amp; 861.89 &amp; 2 &amp; 430.945 &amp; 16.37 &amp; \approx 0.00037 \\
\text{Error} &amp; 315.75 &amp; 12 &amp; 26.312 &amp; &amp; \\
\text{Total} &amp; 1177.64 &amp; 14 &amp; &amp; &amp; \\
\hline
\end{array}\]</span> Thus <span class="math display">\[F_{\mathrm{obs}}=\frac{430.945}{26.312}\approx 16.37.\]</span> Since <span class="math inline">\(p\approx 0.00037&lt;0.01\)</span>, we reject <span class="math inline">\(H_0\)</span> at the <span class="math inline">\(1\%\)</span> significance level. There is strong evidence that at least one brand has a different mean travel distance.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Key idea">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Key idea
</div>
</div>
<div class="callout-body-container callout-body">
<p>How to read the golf-ball result The ANOVA test does not say that all three brands differ from one another. It says that the three means are not all equal. A follow-up comparison, such as pairwise contrasts or a multiple-comparison method, is needed to identify which brand means differ.</p>
</div>
</div>
</section>
<section id="example-smoking-and-heart-rate" class="level1" data-number="28">
<h1 data-number="28"><span class="header-section-number">28</span> Example: Smoking and Heart Rate</h1>
<p>This section gives another full ANOVA computation, emphasizing how sums of squares are computed from treatment totals.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Example 4</strong> (Smoking and heart rate). A study compares heart rate after exercise for four smoking categories. The data are:</p>
<div class="center">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Subject</th>
<th style="text-align: center;">Nonsmoker</th>
<th style="text-align: center;">Light Smoker</th>
<th style="text-align: center;">Moderate Smoker</th>
<th style="text-align: center;">Heavy Smoker</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">69</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">66</td>
<td style="text-align: center;">91</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">52</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">81</td>
<td style="text-align: center;">72</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">71</td>
<td style="text-align: center;">78</td>
<td style="text-align: center;">70</td>
<td style="text-align: center;">81</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">58</td>
<td style="text-align: center;">58</td>
<td style="text-align: center;">77</td>
<td style="text-align: center;">67</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">59</td>
<td style="text-align: center;">62</td>
<td style="text-align: center;">57</td>
<td style="text-align: center;">95</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">65</td>
<td style="text-align: center;">66</td>
<td style="text-align: center;">79</td>
<td style="text-align: center;">84</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(T_j\)</span></td>
<td style="text-align: center;">374</td>
<td style="text-align: center;">379</td>
<td style="text-align: center;">430</td>
<td style="text-align: center;">490</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_j\)</span></td>
<td style="text-align: center;">62.3</td>
<td style="text-align: center;">63.2</td>
<td style="text-align: center;">71.7</td>
<td style="text-align: center;">81.7</td>
</tr>
</tbody>
</table>
</div>
<p>Test <span class="math display">\[H_0: \mu_1=\mu_2=\mu_3=\mu_4\]</span> against the alternative that at least one group mean differs, using <span class="math inline">\(\alpha=0.05\)</span>.</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Solution
</div>
</div>
<div class="callout-body-container callout-body">
<p>There are <span class="math inline">\(k=4\)</span> groups and <span class="math inline">\(n_j=6\)</span> observations in each group, so <span class="math inline">\(N=24\)</span>. The grand mean is <span class="math display">\[\bar{Y}_{\cdot\cdot}=\frac{374+379+430+490}{24}=69.7.\]</span> The treatment sum of squares is <span class="math display">\[\begin{aligned}
\mathrm{SSTR}
&amp;=\sum_{j=1}^{4}n_j(\bar{Y}_j-\bar{Y}_{\cdot\cdot})^2 \\
&amp;=6\left[(62.3-69.7)^2+(63.2-69.7)^2+(71.7-69.7)^2+(81.7-69.7)^2\right] \\
&amp;\approx 1464.125.
\end{aligned}\]</span> The error sum of squares is computed by summing squared deviations within each group: <span class="math display">\[\mathrm{SSE}=\sum_{j=1}^{4}\sum_{i=1}^{6}(Y_{ij}-\bar{Y}_j)^2\approx 1594.833.\]</span> The degrees of freedom are <span class="math display">\[\mathrm{df}_{\mathrm{treat}}=k-1=3,
    \qquad
    \mathrm{df}_{\mathrm{error}}=N-k=20.\]</span> The mean squares are <span class="math display">\[\mathrm{MST}=\frac{1464.125}{3}=488.04,
    \qquad
    \mathrm{MSE}=\frac{1594.833}{20}=79.74.\]</span> Thus <span class="math display">\[F_{\mathrm{obs}}=\frac{\mathrm{MST}}{\mathrm{MSE}}
    =\frac{488.04}{79.74}\approx 6.12.\]</span> The critical value for <span class="math inline">\(\alpha=0.05\)</span> with <span class="math inline">\((3,20)\)</span> degrees of freedom is approximately <span class="math display">\[F_{0.05;3,20}\approx 3.10.\]</span> Since <span class="math display">\[6.12&gt;3.10,\]</span> we reject <span class="math inline">\(H_0\)</span>. The p-value is approximately <span class="math inline">\(0.004\)</span>, which gives the same conclusion.</p>
<p>The ANOVA table is: <span class="math display">\[\begin{array}{lccccc}
\hline
\text{Source} &amp; \mathrm{df}&amp; \text{SS} &amp; \text{MS} &amp; F &amp; p \\
\hline
\text{Treatment} &amp; 3 &amp; 1464.125 &amp; 488.04 &amp; 6.12 &amp; 0.004 \\
\text{Error} &amp; 20 &amp; 1594.833 &amp; 79.74 &amp; &amp; \\
\text{Total} &amp; 23 &amp; 3058.958 &amp; &amp; &amp; \\
\hline
\end{array}\]</span> There is statistically significant evidence that smoking level affects mean heart rate after exercise. At least one group’s mean heart rate differs from the others.</p>
</div>
</div>
</section>
<section id="applications-and-interpretation" class="level1" data-number="29">
<h1 data-number="29"><span class="header-section-number">29</span> Applications and Interpretation</h1>
<p>This section explains what ANOVA conclusions mean in applied work.</p>
<section id="what-anova-tells-us" class="level2" data-number="29.1">
<h2 data-number="29.1" class="anchored" data-anchor-id="what-anova-tells-us"><span class="header-section-number">29.1</span> What ANOVA tells us</h2>
<p>ANOVA is a global test for equality of means.</p>
<p>A significant ANOVA F-test tells us that the data provide evidence against <span class="math display">\[H_0: \mu_1=\cdots=\mu_k.\]</span> It does not automatically identify which group is different. For example, if <span class="math inline">\(k=4\)</span> and the test is significant, then many patterns are possible:</p>
<ul>
<li><p>one group differs from the other three;</p></li>
<li><p>two groups differ from the other two;</p></li>
<li><p>the groups increase or decrease in order;</p></li>
<li><p>all groups have different means.</p></li>
</ul>
</section>
<section id="why-not-just-run-many-t-tests" class="level2" data-number="29.2">
<h2 data-number="29.2" class="anchored" data-anchor-id="why-not-just-run-many-t-tests"><span class="header-section-number">29.2</span> Why not just run many t-tests?</h2>
<p>Multiple pairwise t-tests can inflate the Type I error rate.</p>
<p>If each individual test is run at significance level <span class="math inline">\(0.05\)</span>, then the chance of at least one false positive increases as the number of tests increases. For two independent tests, <span class="math display">\[\mathbb{P}(\text{at least one Type I error})=1-(1-0.05)^2
    =1-0.95^2\approx 0.0975.\]</span> For three independent tests, <span class="math display">\[1-0.95^3\approx 0.143.\]</span> The ANOVA F-test provides a single global test with a controlled Type I error rate.</p>
</section>
<section id="follow-up-analysis-after-anova" class="level2" data-number="29.3">
<h2 data-number="29.3" class="anchored" data-anchor-id="follow-up-analysis-after-anova"><span class="header-section-number">29.3</span> Follow-up analysis after ANOVA</h2>
<p>After rejecting the global ANOVA null, the next step is usually to examine scientifically meaningful comparisons.</p>
<p>Examples of follow-up questions include:</p>
<ul>
<li><p>Which treatment differs from the control?</p></li>
<li><p>Which pair of treatments differ?</p></li>
<li><p>Is the average response under several treatments larger than the control?</p></li>
<li><p>Is there an ordered pattern across treatment levels?</p></li>
</ul>
<p>Such questions can be formulated using contrasts, confidence intervals, or multiple comparison procedures.</p>
</section>
</section>
<section id="design-of-experiments" class="level1" data-number="30">
<h1 data-number="30"><span class="header-section-number">30</span> Design of Experiments</h1>
<p>This section connects ANOVA to the design of experiments, because good design reduces unexplained variation.</p>
<p>Effective experimental design is built on four principles traditionally associated with Ronald Fisher.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Definition 5</strong> (Four principles of experimental design). The four main principles are:</p>
<ol type="1">
<li><p><strong>Control</strong>: Researchers control variables that might influence the outcome, often using a control group as a baseline.</p></li>
<li><p><strong>Randomization</strong>: Subjects or experimental units are randomly assigned to treatment groups.</p></li>
<li><p><strong>Replication</strong>: The experiment is repeated across multiple units so results are not driven by chance.</p></li>
<li><p><strong>Blocking</strong>: Similar experimental units are grouped into blocks to reduce nuisance variability within each block.</p></li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Key idea">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Key idea
</div>
</div>
<div class="callout-body-container callout-body">
<p>Why blocking matters Without blocking, a large nuisance factor may be hidden inside the error term. With blocking, we explicitly model that nuisance factor and remove its contribution from the error sum of squares. This often makes treatment comparisons more sensitive.</p>
</div>
</div>
</section>
<section id="randomized-block-designs" class="level1" data-number="31">
<h1 data-number="31"><span class="header-section-number">31</span> Randomized Block Designs</h1>
<p>This section introduces randomized block designs as a two-way structure with treatments and blocks.</p>
<section id="motivation" class="level2" data-number="31.1">
<h2 data-number="31.1" class="anchored" data-anchor-id="motivation"><span class="header-section-number">31.1</span> Motivation</h2>
<p>A randomized block design is useful when experimental units vary because of a nuisance factor.</p>
<p>Examples of possible blocks include:</p>
<ul>
<li><p>fields or plots of land;</p></li>
<li><p>patients with similar risk levels;</p></li>
<li><p>machines;</p></li>
<li><p>batches;</p></li>
<li><p>days;</p></li>
<li><p>classrooms or sections.</p></li>
</ul>
<p>The goal is to compare treatments within relatively homogeneous blocks.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Definition 6</strong> (Randomized block design). A randomized block design groups similar experimental units into blocks. Each block receives all treatments, usually exactly once. Treatments are randomized within each block.</p>
</div>
</div>
</section>
<section id="when-to-use-a-randomized-block-design" class="level2" data-number="31.2">
<h2 data-number="31.2" class="anchored" data-anchor-id="when-to-use-a-randomized-block-design"><span class="header-section-number">31.2</span> When to Use a Randomized Block Design</h2>
<p>A randomized block design is appropriate when blocks capture an important source of variation.</p>
<p>Use RBD when:</p>
<ol type="1">
<li><p>experimental units can be partitioned into homogeneous blocks;</p></li>
<li><p>variability among blocks is expected to be large;</p></li>
<li><p>variability within blocks is expected to be small;</p></li>
<li><p>the researcher wants to increase power without increasing sample size.</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled" title="Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Example 7</strong> (Fertilizers in blocks). Suppose three fertilizers <span class="math inline">\(A,B,C\)</span> are applied in four blocks. Each block receives all treatments:</p>
<div class="center">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Block</th>
<th style="text-align: center;">A</th>
<th style="text-align: center;">B</th>
<th style="text-align: center;">C</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">27</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">23</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">30</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">24</td>
<td style="text-align: center;">28</td>
</tr>
</tbody>
</table>
</div>
<p>The blocks may differ in productivity. The randomized block design removes between-block variation and improves the sensitivity of treatment comparisons.</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Solution
</div>
</div>
<div class="callout-body-container callout-body">
<p>The treatment means are <span class="math display">\[\bar{Y}_{A\cdot}=\frac{18+16+21+20}{4}=18.75,\]</span> <span class="math display">\[\bar{Y}_{B\cdot}=\frac{22+25+19+24}{4}=22.50,\]</span> <span class="math display">\[\bar{Y}_{C\cdot}=\frac{27+23+30+28}{4}=27.00.\]</span> These means suggest that fertilizer <span class="math inline">\(C\)</span> may produce the largest response. However, ANOVA for a randomized block design formally compares treatments after accounting for block-to-block differences.</p>
</div>
</div>
</section>
<section id="structure-of-a-randomized-block-design" class="level2" data-number="31.3">
<h2 data-number="31.3" class="anchored" data-anchor-id="structure-of-a-randomized-block-design"><span class="header-section-number">31.3</span> Structure of a Randomized Block Design</h2>
<p>The randomized block model includes both treatment effects and block effects.</p>
<p>Let there be <span class="math inline">\(t\)</span> treatments and <span class="math inline">\(b\)</span> blocks. The observation for treatment <span class="math inline">\(i\)</span> in block <span class="math inline">\(j\)</span> is modeled as <span class="math display">\[Y_{ij}=\mu+\tau_i+\beta_j+\epsilon_{ij},
    \qquad i=1,\ldots,t,
    \quad j=1,\ldots,b.\]</span> Here:</p>
<ul>
<li><p><span class="math inline">\(\mu\)</span> is the overall mean;</p></li>
<li><p><span class="math inline">\(\tau_i\)</span> is the treatment effect;</p></li>
<li><p><span class="math inline">\(\beta_j\)</span> is the block effect;</p></li>
<li><p><span class="math inline">\(\epsilon_{ij}\overset{\mathrm{iid}}{\sim}\operatorname{Normal}(0,\sigma^2)\)</span>.</p></li>
</ul>
<p>Because the model is overparameterized, identifiability constraints are typically imposed: <span class="math display">\[\sum_{i=1}^{t}\tau_i=0,
    \qquad
    \sum_{j=1}^{b}\beta_j=0.\]</span></p>
</section>
<section id="hypotheses-for-treatments" class="level2" data-number="31.4">
<h2 data-number="31.4" class="anchored" data-anchor-id="hypotheses-for-treatments"><span class="header-section-number">31.4</span> Hypotheses for Treatments</h2>
<p>The main goal is usually to test whether treatment effects differ after accounting for blocks.</p>
<p>The treatment hypothesis is <span class="math display">\[H_0: \tau_1=\tau_2=\cdots=\tau_t=0\]</span> versus <span class="math display">\[H_1: \tau_i\neq 0 \quad \text{for at least one } i.\]</span> Equivalently, we test whether all treatment means are equal after adjusting for block effects.</p>
</section>
</section>
<section id="computing-sums-of-squares-in-a-randomized-block-design" class="level1" data-number="32">
<h1 data-number="32"><span class="header-section-number">32</span> Computing Sums of Squares in a Randomized Block Design</h1>
<p>This section gives the computational formulas for an RBD ANOVA table.</p>
<p>Let <span class="math display">\[T_i=\sum_{j=1}^{b}Y_{ij}\]</span> be the total for treatment <span class="math inline">\(i\)</span>, and let <span class="math display">\[B_j=\sum_{i=1}^{t}Y_{ij}\]</span> be the total for block <span class="math inline">\(j\)</span>. Let <span class="math display">\[G=\sum_{i=1}^{t}\sum_{j=1}^{b}Y_{ij}\]</span> be the grand total. There are <span class="math inline">\(tb\)</span> total observations.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Definition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Definition 8</strong> (RBD sums of squares). The total sum of squares is <span class="math display">\[\mathrm{SST}_{\mathrm{total}}
    =\sum_{i=1}^{t}\sum_{j=1}^{b}Y_{ij}^2-\frac{G^2}{tb}.\]</span> The treatment sum of squares is <span class="math display">\[\mathrm{SST}_{\mathrm{trt}}
    =\frac{1}{b}\sum_{i=1}^{t}T_i^2-\frac{G^2}{tb}.\]</span> The block sum of squares is <span class="math display">\[\mathrm{SSB}_{\mathrm{block}}
    =\frac{1}{t}\sum_{j=1}^{b}B_j^2-\frac{G^2}{tb}.\]</span> The error sum of squares is <span class="math display">\[\mathrm{SSE}=\mathrm{SST}_{\mathrm{total}}-\mathrm{SST}_{\mathrm{trt}}-\mathrm{SSB}_{\mathrm{block}}.\]</span></p>
</div>
</div>
<section id="anova-table-for-randomized-block-design" class="level2" data-number="32.1">
<h2 data-number="32.1" class="anchored" data-anchor-id="anova-table-for-randomized-block-design"><span class="header-section-number">32.1</span> ANOVA Table for Randomized Block Design</h2>
<p>The RBD ANOVA table separates total variation into treatment variation, block variation, and error variation.</p>
<div class="center">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Source</th>
<th style="text-align: center;">df</th>
<th style="text-align: center;">SS</th>
<th style="text-align: center;">MS</th>
<th style="text-align: center;">F Statistic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Treatments</td>
<td style="text-align: center;"><span class="math inline">\(t-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathrm{SST}_{\mathrm{trt}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathrm{MST}=\mathrm{SST}_{\mathrm{trt}}/(t-1)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(F=\mathrm{MST}/\mathrm{MSE}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Blocks</td>
<td style="text-align: center;"><span class="math inline">\(b-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathrm{SSB}_{\mathrm{block}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathrm{MSB}=\mathrm{SSB}_{\mathrm{block}}/(b-1)\)</span></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Error</td>
<td style="text-align: center;"><span class="math inline">\((t-1)(b-1)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathrm{SSE}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathrm{MSE}=\mathrm{SSE}/[(t-1)(b-1)]\)</span></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: center;"><span class="math inline">\(tb-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mathrm{SST}_{\mathrm{total}}\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</div>
<p>The treatment F-test rejects <span class="math inline">\(H_0\)</span> for large values of <span class="math display">\[F_{\mathrm{trt}}=\frac{\mathrm{MST}}{\mathrm{MSE}}.\]</span> Under the null hypothesis and model assumptions, <span class="math display">\[F_{\mathrm{trt}}\sim F_{t-1,(t-1)(b-1)}.\]</span></p>
</section>
</section>
<section id="example-complete-randomized-block-design-computation" class="level1" data-number="33">
<h1 data-number="33"><span class="header-section-number">33</span> Example: Complete Randomized Block Design Computation</h1>
<p>This section completes the fertilizer example using the randomized block design formulas.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Example 9</strong> (RBD computation for fertilizers). Consider the fertilizer data:</p>
<div class="center">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Block</th>
<th style="text-align: center;">A</th>
<th style="text-align: center;">B</th>
<th style="text-align: center;">C</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">27</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">23</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">30</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">24</td>
<td style="text-align: center;">28</td>
</tr>
</tbody>
</table>
</div>
<p>Compute the randomized block ANOVA table and test for treatment differences.</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Solution
</div>
</div>
<div class="callout-body-container callout-body">
<p>There are <span class="math inline">\(t=3\)</span> treatments and <span class="math inline">\(b=4\)</span> blocks. The treatment totals are <span class="math display">\[T_A=75,\qquad T_B=90,\qquad T_C=108.\]</span> The block totals are <span class="math display">\[B_1=67,\quad B_2=64,\quad B_3=70,\quad B_4=72.\]</span> The grand total is <span class="math display">\[G=273,\]</span> and <span class="math inline">\(tb=12\)</span>.</p>
<p>First compute <span class="math display">\[\sum_{i,j}Y_{ij}^2
    =18^2+22^2+27^2+16^2+25^2+23^2+21^2+19^2+30^2+20^2+24^2+28^2
    =6385.\]</span> Thus <span class="math display">\[\mathrm{SST}_{\mathrm{total}}
    =6385-\frac{273^2}{12}
    =6385-6210.75
    =174.25.\]</span> The treatment sum of squares is <span class="math display">\[\begin{aligned}
\mathrm{SST}_{\mathrm{trt}}
&amp;=\frac{1}{4}(75^2+90^2+108^2)-\frac{273^2}{12} \\
&amp;=\frac{25389}{4}-6210.75 \\
&amp;=136.50.
\end{aligned}\]</span> The block sum of squares is <span class="math display">\[\mathrm{SSB}_{\mathrm{block}}
    =\frac{1}{3}(67^2+64^2+70^2+72^2)-6210.75
    =13.583.\]</span> The error sum of squares is <span class="math display">\[\mathrm{SSE}=174.25-136.50-13.583=24.167.\]</span> The degrees of freedom are <span class="math display">\[\mathrm{df}_{\mathrm{trt}}=t-1=2,
    \quad
    \mathrm{df}_{\mathrm{block}}=b-1=3,
    \quad
    \mathrm{df}_{\mathrm{error}}=(t-1)(b-1)=6,
    \quad
    \mathrm{df}_{\mathrm{total}}=11.\]</span> The mean squares are <span class="math display">\[\mathrm{MST}=\frac{136.50}{2}=68.250,
    \qquad
    \mathrm{MSB}=\frac{13.583}{3}=4.528,
    \qquad
    \mathrm{MSE}=\frac{24.167}{6}=4.028.\]</span> Therefore <span class="math display">\[F_{\mathrm{trt}}=\frac{68.250}{4.028}\approx 16.95.\]</span> The ANOVA table is: <span class="math display">\[\begin{array}{lcccc}
\hline
\text{Source} &amp; \mathrm{df}&amp; \text{SS} &amp; \text{MS} &amp; F \\
\hline
\text{Treatments} &amp; 2 &amp; 136.500 &amp; 68.250 &amp; 16.95 \\
\text{Blocks} &amp; 3 &amp; 13.583 &amp; 4.528 &amp; \\
\text{Error} &amp; 6 &amp; 24.167 &amp; 4.028 &amp; \\
\text{Total} &amp; 11 &amp; 174.250 &amp; &amp; \\
\hline
\end{array}\]</span> The treatment p-value is <span class="math display">\[\mathbb{P}(F_{2,6}&gt;16.95),\]</span> which is small. Thus we reject the null hypothesis of equal treatment effects. There is strong evidence that the fertilizers do not all have the same mean response.</p>
</div>
</div>
</section>
<section id="lab-randomized-block-designs-with-python" class="level1" data-number="34">
<h1 data-number="34"><span class="header-section-number">34</span> Lab: Randomized Block Designs with Python</h1>
<p>This section summarizes the lab-style setup for randomized block designs.</p>
<p>A typical Python lab can use:</p>
<ul>
<li><p>treatments: <span class="math inline">\(3\)</span> fertilizers, for example F1, F2, and NF (no fertilizer);</p></li>
<li><p>blocks: <span class="math inline">\(3\)</span> crop types, for example corn, rice, and wheat;</p></li>
<li><p>response: number of months the crops stayed healthy.</p></li>
</ul>
<p>The model is <span class="math display">\[Y_{ij}=\mu+\tau_i+\beta_j+\epsilon_{ij},
    \qquad \epsilon_{ij}\sim \operatorname{Normal}(0,\sigma^2).\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled" title="Key idea">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Key idea
</div>
</div>
<div class="callout-body-container callout-body">
<p>Practical workflow for an RBD analysis</p>
<ol type="1">
<li><p>Plot the response by treatment and by block.</p></li>
<li><p>Fit a model with treatment and block effects.</p></li>
<li><p>Construct the ANOVA table.</p></li>
<li><p>Test the treatment effect using <span class="math inline">\(F=\mathrm{MST}/\mathrm{MSE}\)</span>.</p></li>
<li><p>Interpret the treatment result after accounting for block variation.</p></li>
</ol>
</div>
</div>
</section>
<section id="practice-problems" class="level1" data-number="35">
<h1 data-number="35"><span class="header-section-number">35</span> Practice Problems</h1>
<p>This section gives practice problems that reinforce one-way ANOVA and randomized block designs.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Practice problem">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Practice problem
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Practice Problem 10</strong> (One-way ANOVA from summary statistics). Suppose three groups have sample sizes <span class="math inline">\(n_1=n_2=n_3=5\)</span>, sample means <span class="math display">\[\bar{x}_1=10,
    \qquad
    \bar{x}_2=14,
    \qquad
    \bar{x}_3=18,\]</span> and sample variances <span class="math display">\[s_1^2=4,
    \qquad
    s_2^2=5,
    \qquad
    s_3^2=6.\]</span> Compute the one-way ANOVA table and the observed F statistic.</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Solution
</div>
</div>
<div class="callout-body-container callout-body">
<p>The total sample size is <span class="math inline">\(N=15\)</span> and <span class="math inline">\(k=3\)</span>. The grand mean is <span class="math display">\[\bar{x}_{\cdot\cdot}=\frac{5(10)+5(14)+5(18)}{15}=14.\]</span> The between-group sum of squares is <span class="math display">\[\mathrm{SSB}=5(10-14)^2+5(14-14)^2+5(18-14)^2=160.\]</span> The within-group sum of squares is <span class="math display">\[\mathrm{SSE}=(5-1)4+(5-1)5+(5-1)6=16+20+24=60.\]</span> Thus <span class="math display">\[\mathrm{MSB}=\frac{160}{2}=80,
    \qquad
    \mathrm{MSE}=\frac{60}{12}=5.\]</span> The observed F statistic is <span class="math display">\[F_{\mathrm{obs}}=\frac{80}{5}=16.\]</span> The ANOVA table is: <span class="math display">\[\begin{array}{lcccc}
\hline
\text{Source} &amp; \text{SS} &amp; \mathrm{df}&amp; \text{MS} &amp; F \\
\hline
\text{Between} &amp; 160 &amp; 2 &amp; 80 &amp; 16 \\
\text{Within} &amp; 60 &amp; 12 &amp; 5 &amp; \\
\text{Total} &amp; 220 &amp; 14 &amp; &amp; \\
\hline
\end{array}\]</span></p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Practice problem">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Practice problem
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Practice Problem 11</strong> (Why blocking can help). Explain why a randomized block design can have more power than a completely randomized one-way ANOVA design.</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Solution
</div>
</div>
<div class="callout-body-container callout-body">
<p>A randomized block design separates nuisance variation due to blocks from random error. In a completely randomized design, block-to-block variation is absorbed into the error term. This can make <span class="math inline">\(\mathrm{MSE}\)</span> large and reduce the F statistic for treatment effects. In an RBD, block variation is removed through the block sum of squares, often making the residual error smaller. A smaller <span class="math inline">\(\mathrm{MSE}\)</span> makes it easier to detect genuine treatment differences.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Practice problem">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Practice problem
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Practice Problem 12</strong> (RBD degrees of freedom). A randomized block design has <span class="math inline">\(t=5\)</span> treatments and <span class="math inline">\(b=6\)</span> blocks. Find the degrees of freedom for treatment, block, error, and total sources of variation.</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Solution
</div>
</div>
<div class="callout-body-container callout-body">
<p>The degrees of freedom are: <span class="math display">\[\mathrm{df}_{\mathrm{treatment}}=t-1=4,\]</span> <span class="math display">\[\mathrm{df}_{\mathrm{block}}=b-1=5,\]</span> <span class="math display">\[\mathrm{df}_{\mathrm{error}}=(t-1)(b-1)=4\cdot 5=20,\]</span> and <span class="math display">\[\mathrm{df}_{\mathrm{total}}=tb-1=30-1=29.\]</span> They add correctly: <span class="math display">\[4+5+20=29.\]</span></p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Practice problem">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Practice problem
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Practice Problem 13</strong> (Treatment F statistic in an RBD). In a randomized block design with <span class="math inline">\(t=4\)</span> treatments and <span class="math inline">\(b=5\)</span> blocks, suppose <span class="math display">\[\mathrm{SST}_{\mathrm{trt}}=90,
    \qquad
    \mathrm{SSE}=60.\]</span> Compute the treatment F statistic.</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Solution
</div>
</div>
<div class="callout-body-container callout-body">
<p>The treatment degrees of freedom are <span class="math display">\[t-1=3.\]</span> The error degrees of freedom are <span class="math display">\[(t-1)(b-1)=3\cdot 4=12.\]</span> Therefore <span class="math display">\[\mathrm{MST}=\frac{90}{3}=30,
    \qquad
    \mathrm{MSE}=\frac{60}{12}=5.\]</span> The treatment F statistic is <span class="math display">\[F=\frac{\mathrm{MST}}{\mathrm{MSE}}=\frac{30}{5}=6.\]</span></p>
</div>
</div>
</section>
<section id="summary" class="level1" data-number="36">
<h1 data-number="36"><span class="header-section-number">36</span> Summary</h1>
<p>This final section summarizes the key ideas from ANOVA applications and randomized block designs.</p>
<ul>
<li><p>One-way ANOVA compares <span class="math inline">\(k\)</span> group means using the ratio <span class="math inline">\(F=\mathrm{MSB}/\mathrm{MSE}\)</span>.</p></li>
<li><p>The ANOVA F-test is a global test: it detects whether at least one group mean differs.</p></li>
<li><p>The sums of squares decomposition is <span class="math display">\[\mathrm{SST}=\mathrm{SSB}+\mathrm{SSE}.\]</span></p></li>
<li><p>Multiple pairwise t-tests can inflate Type I error.</p></li>
<li><p>Good experimental design uses control, randomization, replication, and blocking.</p></li>
<li><p>Randomized block designs reduce nuisance variation by comparing treatments within homogeneous blocks.</p></li>
<li><p>In an RBD, total variation is decomposed into treatment variation, block variation, and error variation.</p></li>
</ul>
<section id="references-and-further-reading" class="level2" data-number="36.1">
<h2 data-number="36.1" class="anchored" data-anchor-id="references-and-further-reading"><span class="header-section-number">36.1</span> References and Further Reading</h2>
<p>9 George Casella and Roger L. Berger, <em>Statistical Inference</em>, 2nd edition. Larry Wasserman, <em>All of Statistics</em>. ProbabilityCourse.com, online probability and statistics resources. Penn State STAT 415 online notes. Harvard Stat 110 online resources. E. Garcia-Portugues, <em>Notes for Predictive Modeling and Statistical Inference</em>.</p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/wanghemath\.github\.io\/Book-ProbabilityStatisticalTheory\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/chapter-18-anova1.html" class="pagination-link" aria-label="Chapter 18: Analysis of Variance I — One-Way ANOVA">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Chapter 18: Analysis of Variance I — One-Way ANOVA</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/chapter-20-bayesian-inference.html" class="pagination-link" aria-label="Chapter 20: Bayesian Inference">
        <span class="nav-page-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Chapter 20: Bayesian Inference</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Chapter 19: Analysis of Variance II — Applications and Randomized Block Designs"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-depth: 3</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">  pdf:</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu"># Analysis of Variance II: Applications and Randomized Block Designs</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>This chapter continues ANOVA by emphasizing **applications, interpretation, experimental design, and randomized block designs**. We review the one-way ANOVA table, work through complete numerical examples, discuss why multiple pairwise tests can inflate Type I error, and introduce blocking as a way to remove nuisance variation from the error term.</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="Topics"}</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>One-way ANOVA review; complete ANOVA computations; ANOVA interpretation; multiple testing; follow-up comparisons; principles of experimental design; control, randomization, replication, and blocking; randomized block design model; RBD sums of squares; RBD ANOVA table; treatment and block effects.</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="fu"># Overview</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>This section shows how ANOVA is used in real data analysis and how experimental design affects the interpretation of ANOVA results.</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>The main topics are:</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>review and summary of one-way ANOVA;</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>complete numerical ANOVA computations;</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>applications and interpretation;</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="ss">4.  </span>principles of experimental design;</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="ss">5.  </span>randomized block designs.</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a><span class="fu"># Review and Summary of One-Way ANOVA</span></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>This section reviews the one-way ANOVA model and the classical ANOVA table before moving to applications.</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a><span class="fu">## Background</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>One-way ANOVA is used when we want to compare the means of several populations or treatment groups.</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>ANOVA is appropriate in two common settings:</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>$k$ independent random samples are drawn from $k$ populations;</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>$k$ different treatments are applied to a homogeneous group of experimental units, which is subdivided into $k$ subgroups.</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>The scientific question is: $$\text{Do the treatment groups have the same population mean, or does at least one treatment differ?}$$</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a><span class="fu">## One-Way ANOVA Model</span></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>The one-way ANOVA model represents each observation as a group mean plus random error.</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>Let $X_{ij}$ be the $j$th observation in group $i$, where $$i=1,\ldots,k, \qquad j=1,\ldots,n_i.$$ The model is $$X_{ij}=\mu_i+\epsilon_{ij},$$ where $\mu_i$ is the mean of group $i$ and $\epsilon_{ij}$ is the random error.</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="Definition"}</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>**Definition 1** (One-way ANOVA assumptions). The classical one-way ANOVA model assumes:</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>the samples are independently selected from the $k$ populations;</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>the $k$ populations are approximately normal;</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>all $k$ population variances are equal;</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a><span class="ss">4.  </span>equivalently, $$\epsilon_{ij}\overset{\text{iid}}{\sim} \operatorname{Normal}(0,\sigma^2).$$</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a><span class="fu">## Classical ANOVA Hypothesis</span></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>The classical ANOVA test asks whether all treatment means are equal.</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>The hypotheses are $$H_0: \mu_1=\mu_2=\cdots=\mu_k$$ versus $$H_1: \mu_i\neq \mu_j \quad \text{for some } i,j.$$</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>Rejecting $H_0$ means that at least one group mean differs from another. It does not immediately tell us which means differ. Follow-up comparisons, contrasts, or multiple-comparison procedures are needed for that question.</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a><span class="fu">## Dot Notation and Means</span></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>Dot notation provides a compact way to write group totals, group means, and the grand mean.</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>Let $$T_{i\cdot}=\sum_{j=1}^{n_i}Y_{ij}$$ be the total for group $i$. Then the group mean is $$\overline{Y}_{i\cdot}=\frac{T_{i\cdot}}{n_i}=\frac{1}{n_i}\sum_{j=1}^{n_i}Y_{ij}.$$ The total sample size is $$N=\sum_{i=1}^k n_i.$$ The grand total is $$T_{\cdot\cdot}=\sum_{i=1}^{k}\sum_{j=1}^{n_i}Y_{ij}=\sum_{i=1}^k T_{i\cdot},$$ and the grand mean is $$\overline{Y}_{\cdot\cdot}=\frac{1}{N}\sum_{i=1}^{k}\sum_{j=1}^{n_i}Y_{ij}</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>    =\frac{1}{N}\sum_{i=1}^{k}T_{i\cdot}</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>    =\frac{1}{N}\sum_{i=1}^{k}n_i\overline{Y}_{i\cdot}.$$</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a><span class="fu">## Partitioning Sums of Squares</span></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>The key idea of ANOVA is to split total variation into between-group variation and within-group variation.</span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="Definition"}</span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>**Definition 2** (Sums of squares). The total sum of squares is $$\mathrm{SST}_{\mathrm{total}}=\sum_{i=1}^k\sum_{j=1}^{n_i}(Y_{ij}-\overline{Y}_{\cdot\cdot})^2.$$ The between-group sum of squares is $$\mathrm{SSB}_{\mathrm{between}}=\sum_{i=1}^k n_i(\overline{Y}_{i\cdot}-\overline{Y}_{\cdot\cdot})^2.$$ The within-group or error sum of squares is $$\mathrm{SSE}_{\mathrm{error}}=\sum_{i=1}^k\sum_{j=1}^{n_i}(Y_{ij}-\overline{Y}_{i\cdot})^2.$$ The fundamental decomposition is $$\mathrm{SST}_{\mathrm{total}}=\mathrm{SSB}_{\mathrm{between}}+\mathrm{SSE}_{\mathrm{error}}.$$</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Key idea"}</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>Interpretation of the decomposition The between-group sum of squares measures how far the group means are from the grand mean. The within-group sum of squares measures random variation around each group mean. If the between-group variation is large compared with the within-group variation, this provides evidence that the treatment means are not all equal.</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a><span class="fu">## Mean Squares and the F Statistic</span></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>The F statistic compares average between-group variation to average within-group variation.</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>Define the mean treatment sum of squares and mean error sum of squares by $$\mathrm{MSB}=\frac{\mathrm{SSB}}{k-1}, \qquad \mathrm{MSE}=\frac{\mathrm{SSE}}{N-k}.$$ Under the ANOVA assumptions, $$\frac{\mathrm{SSE}}{\sigma^2}\sim \chi^2_{N-k}.$$ If $H_0: \mu_1=\cdots=\mu_k$ is true, then $$\frac{\mathrm{SSB}}{\sigma^2}\sim \chi^2_{k-1}.$$ Therefore, under $H_0$, $$F=\frac{\mathrm{MSB}}{\mathrm{MSE}}</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>    =\frac{\mathrm{SSB}/(k-1)}{\mathrm{SSE}/(N-k)}</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>    \sim F_{k-1,N-k}.$$ Large values of $F$ provide evidence against $H_0$.</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a><span class="fu">## The One-Way ANOVA Table</span></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>The ANOVA table organizes the decomposition of variation and the F-test.</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>::: center</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>  Source of Variation    Sum of Squares    df                Mean Square                              F Statistic</span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a>  --------------------- ---------------- ------- ----------------------------------- ----------------------------------------------</span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>  Between groups         $\mathrm{SSB}$   $k-1$   $\mathrm{MSB}=\mathrm{SSB}/(k-1)$   $F_{\mathrm{obs}}=\mathrm{MSB}/\mathrm{MSE}$</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a>  Within groups          $\mathrm{SSE}$   $N-k$   $\mathrm{MSE}=\mathrm{SSE}/(N-k)$  </span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>  Total                  $\mathrm{SST}$   $N-1$                                      </span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>The p-value is $$p\text{-value}=\mathbb{P}\left(F_{k-1,N-k}&gt;F_{\mathrm{obs}}\right).$$</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a><span class="fu"># Example: Comparing Three Golf Ball Brands</span></span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>This section gives a complete one-way ANOVA computation for comparing three treatment means.</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Example"}</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>**Example 3** (Golf ball distance by brand). A test was conducted to compare the mean distance, in yards, traveled by three brands of golf balls hit by a robotic golfer.</span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a>::: center</span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>   Brand A   Brand B   Brand C</span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a>  --------- --------- ---------</span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a><span class="in">    251.2     263.2     269.7</span></span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a><span class="in">    245.1     262.9     263.2</span></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a><span class="in">    248.0     265.0     277.5</span></span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a><span class="in">    251.1     254.5     267.4</span></span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a><span class="in">    260.5     264.3     270.5</span></span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>Test whether the mean distances for the three brands are equal.</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>::: {.callout-caution title="Solution"}</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a>There are $k=3$ groups with $n_1=n_2=n_3=5$, so $N=15$. The sample summaries are: $$\begin{array}{c|ccc}</span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a>\text{Brand} &amp; \bar{x}_i &amp; s_i^2 &amp; n_i <span class="sc">\\</span></span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a>\hline</span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>A &amp; 251.18 &amp; 33.487 &amp; 5 <span class="sc">\\</span></span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a>B &amp; 261.985 &amp; 18.197 &amp; 5 <span class="sc">\\</span></span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>C &amp; 269.66 &amp; 27.253 &amp; 5</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>\end{array}$$ The grand mean is $$\bar{x}_{\cdot\cdot}</span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>    =\frac{5(251.18)+5(261.985)+5(269.66)}{15}</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a>    \approx 260.94.$$ The between-group sum of squares is $$\begin{aligned}</span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a>\mathrm{SSB}</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a>&amp;=\sum_{i=1}^3 n_i(\bar{x}_i-\bar{x}_{\cdot\cdot})^2 <span class="sc">\\</span></span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a>&amp;=5(251.18-260.94)^2+5(261.985-260.94)^2+5(269.66-260.94)^2 <span class="sc">\\</span></span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a>&amp;\approx 861.89.</span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a>\end{aligned}$$ The within-group sum of squares is $$\mathrm{SSE}=\sum_{i=1}^3(n_i-1)s_i^2</span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a>    =4(33.487+18.197+27.253)</span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a>    \approx 315.75.$$ The total sum of squares is $$\mathrm{SST}=\mathrm{SSB}+\mathrm{SSE}\approx 861.89+315.75=1177.64.$$ The ANOVA table is: $$\begin{array}{lccccc}</span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a>\hline</span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a>\text{Source} &amp; \text{SS} &amp; \text{df} &amp; \text{MS} &amp; F &amp; p\text{-value} <span class="sc">\\</span></span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a>\hline</span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a>\text{Treatment} &amp; 861.89 &amp; 2 &amp; 430.945 &amp; 16.37 &amp; \approx 0.00037 <span class="sc">\\</span></span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a>\text{Error} &amp; 315.75 &amp; 12 &amp; 26.312 &amp; &amp; <span class="sc">\\</span></span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a>\text{Total} &amp; 1177.64 &amp; 14 &amp; &amp; &amp; <span class="sc">\\</span></span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a>\hline</span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a>\end{array}$$ Thus $$F_{\mathrm{obs}}=\frac{430.945}{26.312}\approx 16.37.$$ Since $p\approx 0.00037&lt;0.01$, we reject $H_0$ at the $1\%$ significance level. There is strong evidence that at least one brand has a different mean travel distance.</span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Key idea"}</span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a>How to read the golf-ball result The ANOVA test does not say that all three brands differ from one another. It says that the three means are not all equal. A follow-up comparison, such as pairwise contrasts or a multiple-comparison method, is needed to identify which brand means differ.</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a><span class="fu"># Example: Smoking and Heart Rate</span></span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a>This section gives another full ANOVA computation, emphasizing how sums of squares are computed from treatment totals.</span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Example"}</span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a>**Example 4** (Smoking and heart rate). A study compares heart rate after exercise for four smoking categories. The data are:</span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a>::: center</span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a>     Subject     Nonsmoker   Light Smoker   Moderate Smoker   Heavy Smoker</span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a>  ------------- ----------- -------------- ----------------- --------------</span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a><span class="in">        1           69            55              66               91</span></span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a><span class="in">        2           52            60              81               72</span></span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a><span class="in">        3           71            78              70               81</span></span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a><span class="in">        4           58            58              77               67</span></span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a><span class="in">        5           59            62              57               95</span></span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a><span class="in">        6           65            66              79               84</span></span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a><span class="in">      $T_j$         374          379              430             490</span></span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a>   $\bar{Y}_j$     62.3          63.2            71.7             81.7</span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a>Test $$H_0: \mu_1=\mu_2=\mu_3=\mu_4$$ against the alternative that at least one group mean differs, using $\alpha=0.05$.</span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a>::: {.callout-caution title="Solution"}</span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a>There are $k=4$ groups and $n_j=6$ observations in each group, so $N=24$. The grand mean is $$\bar{Y}_{\cdot\cdot}=\frac{374+379+430+490}{24}=69.7.$$ The treatment sum of squares is $$\begin{aligned}</span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a>\mathrm{SSTR}</span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a>&amp;=\sum_{j=1}^{4}n_j(\bar{Y}_j-\bar{Y}_{\cdot\cdot})^2 <span class="sc">\\</span></span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a>&amp;=6\left<span class="co">[</span><span class="ot">(62.3-69.7)^2+(63.2-69.7)^2+(71.7-69.7)^2+(81.7-69.7)^2\right</span><span class="co">]</span> <span class="sc">\\</span></span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a>&amp;\approx 1464.125.</span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a>\end{aligned}$$ The error sum of squares is computed by summing squared deviations within each group: $$\mathrm{SSE}=\sum_{j=1}^{4}\sum_{i=1}^{6}(Y_{ij}-\bar{Y}_j)^2\approx 1594.833.$$ The degrees of freedom are $$\mathrm{df}_{\mathrm{treat}}=k-1=3,</span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a>    \qquad</span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a>    \mathrm{df}_{\mathrm{error}}=N-k=20.$$ The mean squares are $$\mathrm{MST}=\frac{1464.125}{3}=488.04,</span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a>    \qquad</span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a>    \mathrm{MSE}=\frac{1594.833}{20}=79.74.$$ Thus $$F_{\mathrm{obs}}=\frac{\mathrm{MST}}{\mathrm{MSE}}</span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a>    =\frac{488.04}{79.74}\approx 6.12.$$ The critical value for $\alpha=0.05$ with $(3,20)$ degrees of freedom is approximately $$F_{0.05;3,20}\approx 3.10.$$ Since $$6.12&gt;3.10,$$ we reject $H_0$. The p-value is approximately $0.004$, which gives the same conclusion.</span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a>The ANOVA table is: $$\begin{array}{lccccc}</span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a>\hline</span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a>\text{Source} &amp; \mathrm{df}&amp; \text{SS} &amp; \text{MS} &amp; F &amp; p <span class="sc">\\</span></span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a>\hline</span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a>\text{Treatment} &amp; 3 &amp; 1464.125 &amp; 488.04 &amp; 6.12 &amp; 0.004 <span class="sc">\\</span></span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a>\text{Error} &amp; 20 &amp; 1594.833 &amp; 79.74 &amp; &amp; <span class="sc">\\</span></span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a>\text{Total} &amp; 23 &amp; 3058.958 &amp; &amp; &amp; <span class="sc">\\</span></span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a>\hline</span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a>\end{array}$$ There is statistically significant evidence that smoking level affects mean heart rate after exercise. At least one group's mean heart rate differs from the others.</span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a><span class="fu"># Applications and Interpretation</span></span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a>This section explains what ANOVA conclusions mean in applied work.</span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a><span class="fu">## What ANOVA tells us</span></span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a>ANOVA is a global test for equality of means.</span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a>A significant ANOVA F-test tells us that the data provide evidence against $$H_0: \mu_1=\cdots=\mu_k.$$ It does not automatically identify which group is different. For example, if $k=4$ and the test is significant, then many patterns are possible:</span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>one group differs from the other three;</span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>two groups differ from the other two;</span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>the groups increase or decrease in order;</span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>all groups have different means.</span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a><span class="fu">## Why not just run many t-tests?</span></span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a>Multiple pairwise t-tests can inflate the Type I error rate.</span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a>If each individual test is run at significance level $0.05$, then the chance of at least one false positive increases as the number of tests increases. For two independent tests, $$\mathbb{P}(\text{at least one Type I error})=1-(1-0.05)^2</span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a>    =1-0.95^2\approx 0.0975.$$ For three independent tests, $$1-0.95^3\approx 0.143.$$ The ANOVA F-test provides a single global test with a controlled Type I error rate.</span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a><span class="fu">## Follow-up analysis after ANOVA</span></span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a>After rejecting the global ANOVA null, the next step is usually to examine scientifically meaningful comparisons.</span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a>Examples of follow-up questions include:</span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Which treatment differs from the control?</span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Which pair of treatments differ?</span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Is the average response under several treatments larger than the control?</span>
<span id="cb1-260"><a href="#cb1-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-261"><a href="#cb1-261" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Is there an ordered pattern across treatment levels?</span>
<span id="cb1-262"><a href="#cb1-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a>Such questions can be formulated using contrasts, confidence intervals, or multiple comparison procedures.</span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a><span class="fu"># Design of Experiments</span></span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a>This section connects ANOVA to the design of experiments, because good design reduces unexplained variation.</span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a>Effective experimental design is built on four principles traditionally associated with Ronald Fisher.</span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="Definition"}</span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a>**Definition 5** (Four principles of experimental design). The four main principles are:</span>
<span id="cb1-273"><a href="#cb1-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-274"><a href="#cb1-274" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>**Control**: Researchers control variables that might influence the outcome, often using a control group as a baseline.</span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>**Randomization**: Subjects or experimental units are randomly assigned to treatment groups.</span>
<span id="cb1-277"><a href="#cb1-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-278"><a href="#cb1-278" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>**Replication**: The experiment is repeated across multiple units so results are not driven by chance.</span>
<span id="cb1-279"><a href="#cb1-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-280"><a href="#cb1-280" aria-hidden="true" tabindex="-1"></a><span class="ss">4.  </span>**Blocking**: Similar experimental units are grouped into blocks to reduce nuisance variability within each block.</span>
<span id="cb1-281"><a href="#cb1-281" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-282"><a href="#cb1-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-283"><a href="#cb1-283" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Key idea"}</span>
<span id="cb1-284"><a href="#cb1-284" aria-hidden="true" tabindex="-1"></a>Why blocking matters Without blocking, a large nuisance factor may be hidden inside the error term. With blocking, we explicitly model that nuisance factor and remove its contribution from the error sum of squares. This often makes treatment comparisons more sensitive.</span>
<span id="cb1-285"><a href="#cb1-285" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-286"><a href="#cb1-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-287"><a href="#cb1-287" aria-hidden="true" tabindex="-1"></a><span class="fu"># Randomized Block Designs</span></span>
<span id="cb1-288"><a href="#cb1-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-289"><a href="#cb1-289" aria-hidden="true" tabindex="-1"></a>This section introduces randomized block designs as a two-way structure with treatments and blocks.</span>
<span id="cb1-290"><a href="#cb1-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-291"><a href="#cb1-291" aria-hidden="true" tabindex="-1"></a><span class="fu">## Motivation</span></span>
<span id="cb1-292"><a href="#cb1-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-293"><a href="#cb1-293" aria-hidden="true" tabindex="-1"></a>A randomized block design is useful when experimental units vary because of a nuisance factor.</span>
<span id="cb1-294"><a href="#cb1-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-295"><a href="#cb1-295" aria-hidden="true" tabindex="-1"></a>Examples of possible blocks include:</span>
<span id="cb1-296"><a href="#cb1-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-297"><a href="#cb1-297" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>fields or plots of land;</span>
<span id="cb1-298"><a href="#cb1-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-299"><a href="#cb1-299" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>patients with similar risk levels;</span>
<span id="cb1-300"><a href="#cb1-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-301"><a href="#cb1-301" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>machines;</span>
<span id="cb1-302"><a href="#cb1-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-303"><a href="#cb1-303" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>batches;</span>
<span id="cb1-304"><a href="#cb1-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-305"><a href="#cb1-305" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>days;</span>
<span id="cb1-306"><a href="#cb1-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-307"><a href="#cb1-307" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>classrooms or sections.</span>
<span id="cb1-308"><a href="#cb1-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-309"><a href="#cb1-309" aria-hidden="true" tabindex="-1"></a>The goal is to compare treatments within relatively homogeneous blocks.</span>
<span id="cb1-310"><a href="#cb1-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-311"><a href="#cb1-311" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="Definition"}</span>
<span id="cb1-312"><a href="#cb1-312" aria-hidden="true" tabindex="-1"></a>**Definition 6** (Randomized block design). A randomized block design groups similar experimental units into blocks. Each block receives all treatments, usually exactly once. Treatments are randomized within each block.</span>
<span id="cb1-313"><a href="#cb1-313" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-314"><a href="#cb1-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-315"><a href="#cb1-315" aria-hidden="true" tabindex="-1"></a><span class="fu">## When to Use a Randomized Block Design</span></span>
<span id="cb1-316"><a href="#cb1-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-317"><a href="#cb1-317" aria-hidden="true" tabindex="-1"></a>A randomized block design is appropriate when blocks capture an important source of variation.</span>
<span id="cb1-318"><a href="#cb1-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-319"><a href="#cb1-319" aria-hidden="true" tabindex="-1"></a>Use RBD when:</span>
<span id="cb1-320"><a href="#cb1-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-321"><a href="#cb1-321" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>experimental units can be partitioned into homogeneous blocks;</span>
<span id="cb1-322"><a href="#cb1-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-323"><a href="#cb1-323" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>variability among blocks is expected to be large;</span>
<span id="cb1-324"><a href="#cb1-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-325"><a href="#cb1-325" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>variability within blocks is expected to be small;</span>
<span id="cb1-326"><a href="#cb1-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-327"><a href="#cb1-327" aria-hidden="true" tabindex="-1"></a><span class="ss">4.  </span>the researcher wants to increase power without increasing sample size.</span>
<span id="cb1-328"><a href="#cb1-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-329"><a href="#cb1-329" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Example"}</span>
<span id="cb1-330"><a href="#cb1-330" aria-hidden="true" tabindex="-1"></a>**Example 7** (Fertilizers in blocks). Suppose three fertilizers $A,B,C$ are applied in four blocks. Each block receives all treatments:</span>
<span id="cb1-331"><a href="#cb1-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-332"><a href="#cb1-332" aria-hidden="true" tabindex="-1"></a>::: center</span>
<span id="cb1-333"><a href="#cb1-333" aria-hidden="true" tabindex="-1"></a>   Block   A    B    C</span>
<span id="cb1-334"><a href="#cb1-334" aria-hidden="true" tabindex="-1"></a>  ------- ---- ---- ----</span>
<span id="cb1-335"><a href="#cb1-335" aria-hidden="true" tabindex="-1"></a><span class="in">     1     18   22   27</span></span>
<span id="cb1-336"><a href="#cb1-336" aria-hidden="true" tabindex="-1"></a><span class="in">     2     16   25   23</span></span>
<span id="cb1-337"><a href="#cb1-337" aria-hidden="true" tabindex="-1"></a><span class="in">     3     21   19   30</span></span>
<span id="cb1-338"><a href="#cb1-338" aria-hidden="true" tabindex="-1"></a><span class="in">     4     20   24   28</span></span>
<span id="cb1-339"><a href="#cb1-339" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-340"><a href="#cb1-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-341"><a href="#cb1-341" aria-hidden="true" tabindex="-1"></a>The blocks may differ in productivity. The randomized block design removes between-block variation and improves the sensitivity of treatment comparisons.</span>
<span id="cb1-342"><a href="#cb1-342" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-343"><a href="#cb1-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-344"><a href="#cb1-344" aria-hidden="true" tabindex="-1"></a>::: {.callout-caution title="Solution"}</span>
<span id="cb1-345"><a href="#cb1-345" aria-hidden="true" tabindex="-1"></a>The treatment means are $$\bar{Y}_{A\cdot}=\frac{18+16+21+20}{4}=18.75,$$ $$\bar{Y}_{B\cdot}=\frac{22+25+19+24}{4}=22.50,$$ $$\bar{Y}_{C\cdot}=\frac{27+23+30+28}{4}=27.00.$$ These means suggest that fertilizer $C$ may produce the largest response. However, ANOVA for a randomized block design formally compares treatments after accounting for block-to-block differences.</span>
<span id="cb1-346"><a href="#cb1-346" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-347"><a href="#cb1-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-348"><a href="#cb1-348" aria-hidden="true" tabindex="-1"></a><span class="fu">## Structure of a Randomized Block Design</span></span>
<span id="cb1-349"><a href="#cb1-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-350"><a href="#cb1-350" aria-hidden="true" tabindex="-1"></a>The randomized block model includes both treatment effects and block effects.</span>
<span id="cb1-351"><a href="#cb1-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-352"><a href="#cb1-352" aria-hidden="true" tabindex="-1"></a>Let there be $t$ treatments and $b$ blocks. The observation for treatment $i$ in block $j$ is modeled as $$Y_{ij}=\mu+\tau_i+\beta_j+\epsilon_{ij},</span>
<span id="cb1-353"><a href="#cb1-353" aria-hidden="true" tabindex="-1"></a>    \qquad i=1,\ldots,t,</span>
<span id="cb1-354"><a href="#cb1-354" aria-hidden="true" tabindex="-1"></a>    \quad j=1,\ldots,b.$$ Here:</span>
<span id="cb1-355"><a href="#cb1-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-356"><a href="#cb1-356" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>$\mu$ is the overall mean;</span>
<span id="cb1-357"><a href="#cb1-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-358"><a href="#cb1-358" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>$\tau_i$ is the treatment effect;</span>
<span id="cb1-359"><a href="#cb1-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-360"><a href="#cb1-360" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>$\beta_j$ is the block effect;</span>
<span id="cb1-361"><a href="#cb1-361" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-362"><a href="#cb1-362" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>$\epsilon_{ij}\overset{\mathrm{iid}}{\sim}\operatorname{Normal}(0,\sigma^2)$.</span>
<span id="cb1-363"><a href="#cb1-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-364"><a href="#cb1-364" aria-hidden="true" tabindex="-1"></a>Because the model is overparameterized, identifiability constraints are typically imposed: $$\sum_{i=1}^{t}\tau_i=0,</span>
<span id="cb1-365"><a href="#cb1-365" aria-hidden="true" tabindex="-1"></a>    \qquad</span>
<span id="cb1-366"><a href="#cb1-366" aria-hidden="true" tabindex="-1"></a>    \sum_{j=1}^{b}\beta_j=0.$$</span>
<span id="cb1-367"><a href="#cb1-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-368"><a href="#cb1-368" aria-hidden="true" tabindex="-1"></a><span class="fu">## Hypotheses for Treatments</span></span>
<span id="cb1-369"><a href="#cb1-369" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-370"><a href="#cb1-370" aria-hidden="true" tabindex="-1"></a>The main goal is usually to test whether treatment effects differ after accounting for blocks.</span>
<span id="cb1-371"><a href="#cb1-371" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-372"><a href="#cb1-372" aria-hidden="true" tabindex="-1"></a>The treatment hypothesis is $$H_0: \tau_1=\tau_2=\cdots=\tau_t=0$$ versus $$H_1: \tau_i\neq 0 \quad \text{for at least one } i.$$ Equivalently, we test whether all treatment means are equal after adjusting for block effects.</span>
<span id="cb1-373"><a href="#cb1-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-374"><a href="#cb1-374" aria-hidden="true" tabindex="-1"></a><span class="fu"># Computing Sums of Squares in a Randomized Block Design</span></span>
<span id="cb1-375"><a href="#cb1-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-376"><a href="#cb1-376" aria-hidden="true" tabindex="-1"></a>This section gives the computational formulas for an RBD ANOVA table.</span>
<span id="cb1-377"><a href="#cb1-377" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-378"><a href="#cb1-378" aria-hidden="true" tabindex="-1"></a>Let $$T_i=\sum_{j=1}^{b}Y_{ij}$$ be the total for treatment $i$, and let $$B_j=\sum_{i=1}^{t}Y_{ij}$$ be the total for block $j$. Let $$G=\sum_{i=1}^{t}\sum_{j=1}^{b}Y_{ij}$$ be the grand total. There are $tb$ total observations.</span>
<span id="cb1-379"><a href="#cb1-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-380"><a href="#cb1-380" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="Definition"}</span>
<span id="cb1-381"><a href="#cb1-381" aria-hidden="true" tabindex="-1"></a>**Definition 8** (RBD sums of squares). The total sum of squares is $$\mathrm{SST}_{\mathrm{total}}</span>
<span id="cb1-382"><a href="#cb1-382" aria-hidden="true" tabindex="-1"></a>    =\sum_{i=1}^{t}\sum_{j=1}^{b}Y_{ij}^2-\frac{G^2}{tb}.$$ The treatment sum of squares is $$\mathrm{SST}_{\mathrm{trt}}</span>
<span id="cb1-383"><a href="#cb1-383" aria-hidden="true" tabindex="-1"></a>    =\frac{1}{b}\sum_{i=1}^{t}T_i^2-\frac{G^2}{tb}.$$ The block sum of squares is $$\mathrm{SSB}_{\mathrm{block}}</span>
<span id="cb1-384"><a href="#cb1-384" aria-hidden="true" tabindex="-1"></a>    =\frac{1}{t}\sum_{j=1}^{b}B_j^2-\frac{G^2}{tb}.$$ The error sum of squares is $$\mathrm{SSE}=\mathrm{SST}_{\mathrm{total}}-\mathrm{SST}_{\mathrm{trt}}-\mathrm{SSB}_{\mathrm{block}}.$$</span>
<span id="cb1-385"><a href="#cb1-385" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-386"><a href="#cb1-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-387"><a href="#cb1-387" aria-hidden="true" tabindex="-1"></a><span class="fu">## ANOVA Table for Randomized Block Design</span></span>
<span id="cb1-388"><a href="#cb1-388" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-389"><a href="#cb1-389" aria-hidden="true" tabindex="-1"></a>The RBD ANOVA table separates total variation into treatment variation, block variation, and error variation.</span>
<span id="cb1-390"><a href="#cb1-390" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-391"><a href="#cb1-391" aria-hidden="true" tabindex="-1"></a>::: center</span>
<span id="cb1-392"><a href="#cb1-392" aria-hidden="true" tabindex="-1"></a>  Source             df                      SS                                          MS                                    F Statistic</span>
<span id="cb1-393"><a href="#cb1-393" aria-hidden="true" tabindex="-1"></a>  ------------ -------------- --------------------------------- ---------------------------------------------------- -------------------------------</span>
<span id="cb1-394"><a href="#cb1-394" aria-hidden="true" tabindex="-1"></a>  Treatments       $t-1$        $\mathrm{SST}_{\mathrm{trt}}$     $\mathrm{MST}=\mathrm{SST}_{\mathrm{trt}}/(t-1)$    $F=\mathrm{MST}/\mathrm{MSE}$</span>
<span id="cb1-395"><a href="#cb1-395" aria-hidden="true" tabindex="-1"></a>  Blocks           $b-1$       $\mathrm{SSB}_{\mathrm{block}}$   $\mathrm{MSB}=\mathrm{SSB}_{\mathrm{block}}/(b-1)$  </span>
<span id="cb1-396"><a href="#cb1-396" aria-hidden="true" tabindex="-1"></a>  Error         $(t-1)(b-1)$           $\mathrm{SSE}$                 $\mathrm{MSE}=\mathrm{SSE}/<span class="co">[</span><span class="ot">(t-1)(b-1)</span><span class="co">]</span>$       </span>
<span id="cb1-397"><a href="#cb1-397" aria-hidden="true" tabindex="-1"></a>  Total            $tb-1$      $\mathrm{SST}_{\mathrm{total}}$                                                       </span>
<span id="cb1-398"><a href="#cb1-398" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-399"><a href="#cb1-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-400"><a href="#cb1-400" aria-hidden="true" tabindex="-1"></a>The treatment F-test rejects $H_0$ for large values of $$F_{\mathrm{trt}}=\frac{\mathrm{MST}}{\mathrm{MSE}}.$$ Under the null hypothesis and model assumptions, $$F_{\mathrm{trt}}\sim F_{t-1,(t-1)(b-1)}.$$</span>
<span id="cb1-401"><a href="#cb1-401" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-402"><a href="#cb1-402" aria-hidden="true" tabindex="-1"></a><span class="fu"># Example: Complete Randomized Block Design Computation</span></span>
<span id="cb1-403"><a href="#cb1-403" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-404"><a href="#cb1-404" aria-hidden="true" tabindex="-1"></a>This section completes the fertilizer example using the randomized block design formulas.</span>
<span id="cb1-405"><a href="#cb1-405" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-406"><a href="#cb1-406" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Example"}</span>
<span id="cb1-407"><a href="#cb1-407" aria-hidden="true" tabindex="-1"></a>**Example 9** (RBD computation for fertilizers). Consider the fertilizer data:</span>
<span id="cb1-408"><a href="#cb1-408" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-409"><a href="#cb1-409" aria-hidden="true" tabindex="-1"></a>::: center</span>
<span id="cb1-410"><a href="#cb1-410" aria-hidden="true" tabindex="-1"></a>   Block   A    B    C</span>
<span id="cb1-411"><a href="#cb1-411" aria-hidden="true" tabindex="-1"></a>  ------- ---- ---- ----</span>
<span id="cb1-412"><a href="#cb1-412" aria-hidden="true" tabindex="-1"></a><span class="in">     1     18   22   27</span></span>
<span id="cb1-413"><a href="#cb1-413" aria-hidden="true" tabindex="-1"></a><span class="in">     2     16   25   23</span></span>
<span id="cb1-414"><a href="#cb1-414" aria-hidden="true" tabindex="-1"></a><span class="in">     3     21   19   30</span></span>
<span id="cb1-415"><a href="#cb1-415" aria-hidden="true" tabindex="-1"></a><span class="in">     4     20   24   28</span></span>
<span id="cb1-416"><a href="#cb1-416" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-417"><a href="#cb1-417" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-418"><a href="#cb1-418" aria-hidden="true" tabindex="-1"></a>Compute the randomized block ANOVA table and test for treatment differences.</span>
<span id="cb1-419"><a href="#cb1-419" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-420"><a href="#cb1-420" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-421"><a href="#cb1-421" aria-hidden="true" tabindex="-1"></a>::: {.callout-caution title="Solution"}</span>
<span id="cb1-422"><a href="#cb1-422" aria-hidden="true" tabindex="-1"></a>There are $t=3$ treatments and $b=4$ blocks. The treatment totals are $$T_A=75,\qquad T_B=90,\qquad T_C=108.$$ The block totals are $$B_1=67,\quad B_2=64,\quad B_3=70,\quad B_4=72.$$ The grand total is $$G=273,$$ and $tb=12$.</span>
<span id="cb1-423"><a href="#cb1-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-424"><a href="#cb1-424" aria-hidden="true" tabindex="-1"></a>First compute $$\sum_{i,j}Y_{ij}^2</span>
<span id="cb1-425"><a href="#cb1-425" aria-hidden="true" tabindex="-1"></a>    =18^2+22^2+27^2+16^2+25^2+23^2+21^2+19^2+30^2+20^2+24^2+28^2</span>
<span id="cb1-426"><a href="#cb1-426" aria-hidden="true" tabindex="-1"></a>    =6385.$$ Thus $$\mathrm{SST}_{\mathrm{total}}</span>
<span id="cb1-427"><a href="#cb1-427" aria-hidden="true" tabindex="-1"></a>    =6385-\frac{273^2}{12}</span>
<span id="cb1-428"><a href="#cb1-428" aria-hidden="true" tabindex="-1"></a>    =6385-6210.75</span>
<span id="cb1-429"><a href="#cb1-429" aria-hidden="true" tabindex="-1"></a>    =174.25.$$ The treatment sum of squares is $$\begin{aligned}</span>
<span id="cb1-430"><a href="#cb1-430" aria-hidden="true" tabindex="-1"></a>\mathrm{SST}_{\mathrm{trt}}</span>
<span id="cb1-431"><a href="#cb1-431" aria-hidden="true" tabindex="-1"></a>&amp;=\frac{1}{4}(75^2+90^2+108^2)-\frac{273^2}{12} <span class="sc">\\</span></span>
<span id="cb1-432"><a href="#cb1-432" aria-hidden="true" tabindex="-1"></a>&amp;=\frac{25389}{4}-6210.75 <span class="sc">\\</span></span>
<span id="cb1-433"><a href="#cb1-433" aria-hidden="true" tabindex="-1"></a>&amp;=136.50.</span>
<span id="cb1-434"><a href="#cb1-434" aria-hidden="true" tabindex="-1"></a>\end{aligned}$$ The block sum of squares is $$\mathrm{SSB}_{\mathrm{block}}</span>
<span id="cb1-435"><a href="#cb1-435" aria-hidden="true" tabindex="-1"></a>    =\frac{1}{3}(67^2+64^2+70^2+72^2)-6210.75</span>
<span id="cb1-436"><a href="#cb1-436" aria-hidden="true" tabindex="-1"></a>    =13.583.$$ The error sum of squares is $$\mathrm{SSE}=174.25-136.50-13.583=24.167.$$ The degrees of freedom are $$\mathrm{df}_{\mathrm{trt}}=t-1=2,</span>
<span id="cb1-437"><a href="#cb1-437" aria-hidden="true" tabindex="-1"></a>    \quad</span>
<span id="cb1-438"><a href="#cb1-438" aria-hidden="true" tabindex="-1"></a>    \mathrm{df}_{\mathrm{block}}=b-1=3,</span>
<span id="cb1-439"><a href="#cb1-439" aria-hidden="true" tabindex="-1"></a>    \quad</span>
<span id="cb1-440"><a href="#cb1-440" aria-hidden="true" tabindex="-1"></a>    \mathrm{df}_{\mathrm{error}}=(t-1)(b-1)=6,</span>
<span id="cb1-441"><a href="#cb1-441" aria-hidden="true" tabindex="-1"></a>    \quad</span>
<span id="cb1-442"><a href="#cb1-442" aria-hidden="true" tabindex="-1"></a>    \mathrm{df}_{\mathrm{total}}=11.$$ The mean squares are $$\mathrm{MST}=\frac{136.50}{2}=68.250,</span>
<span id="cb1-443"><a href="#cb1-443" aria-hidden="true" tabindex="-1"></a>    \qquad</span>
<span id="cb1-444"><a href="#cb1-444" aria-hidden="true" tabindex="-1"></a>    \mathrm{MSB}=\frac{13.583}{3}=4.528,</span>
<span id="cb1-445"><a href="#cb1-445" aria-hidden="true" tabindex="-1"></a>    \qquad</span>
<span id="cb1-446"><a href="#cb1-446" aria-hidden="true" tabindex="-1"></a>    \mathrm{MSE}=\frac{24.167}{6}=4.028.$$ Therefore $$F_{\mathrm{trt}}=\frac{68.250}{4.028}\approx 16.95.$$ The ANOVA table is: $$\begin{array}{lcccc}</span>
<span id="cb1-447"><a href="#cb1-447" aria-hidden="true" tabindex="-1"></a>\hline</span>
<span id="cb1-448"><a href="#cb1-448" aria-hidden="true" tabindex="-1"></a>\text{Source} &amp; \mathrm{df}&amp; \text{SS} &amp; \text{MS} &amp; F <span class="sc">\\</span></span>
<span id="cb1-449"><a href="#cb1-449" aria-hidden="true" tabindex="-1"></a>\hline</span>
<span id="cb1-450"><a href="#cb1-450" aria-hidden="true" tabindex="-1"></a>\text{Treatments} &amp; 2 &amp; 136.500 &amp; 68.250 &amp; 16.95 <span class="sc">\\</span></span>
<span id="cb1-451"><a href="#cb1-451" aria-hidden="true" tabindex="-1"></a>\text{Blocks} &amp; 3 &amp; 13.583 &amp; 4.528 &amp; <span class="sc">\\</span></span>
<span id="cb1-452"><a href="#cb1-452" aria-hidden="true" tabindex="-1"></a>\text{Error} &amp; 6 &amp; 24.167 &amp; 4.028 &amp; <span class="sc">\\</span></span>
<span id="cb1-453"><a href="#cb1-453" aria-hidden="true" tabindex="-1"></a>\text{Total} &amp; 11 &amp; 174.250 &amp; &amp; <span class="sc">\\</span></span>
<span id="cb1-454"><a href="#cb1-454" aria-hidden="true" tabindex="-1"></a>\hline</span>
<span id="cb1-455"><a href="#cb1-455" aria-hidden="true" tabindex="-1"></a>\end{array}$$ The treatment p-value is $$\mathbb{P}(F_{2,6}&gt;16.95),$$ which is small. Thus we reject the null hypothesis of equal treatment effects. There is strong evidence that the fertilizers do not all have the same mean response.</span>
<span id="cb1-456"><a href="#cb1-456" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-457"><a href="#cb1-457" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-458"><a href="#cb1-458" aria-hidden="true" tabindex="-1"></a><span class="fu"># Lab: Randomized Block Designs with Python</span></span>
<span id="cb1-459"><a href="#cb1-459" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-460"><a href="#cb1-460" aria-hidden="true" tabindex="-1"></a>This section summarizes the lab-style setup for randomized block designs.</span>
<span id="cb1-461"><a href="#cb1-461" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-462"><a href="#cb1-462" aria-hidden="true" tabindex="-1"></a>A typical Python lab can use:</span>
<span id="cb1-463"><a href="#cb1-463" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-464"><a href="#cb1-464" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>treatments: $3$ fertilizers, for example F1, F2, and NF (no fertilizer);</span>
<span id="cb1-465"><a href="#cb1-465" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-466"><a href="#cb1-466" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>blocks: $3$ crop types, for example corn, rice, and wheat;</span>
<span id="cb1-467"><a href="#cb1-467" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-468"><a href="#cb1-468" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>response: number of months the crops stayed healthy.</span>
<span id="cb1-469"><a href="#cb1-469" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-470"><a href="#cb1-470" aria-hidden="true" tabindex="-1"></a>The model is $$Y_{ij}=\mu+\tau_i+\beta_j+\epsilon_{ij},</span>
<span id="cb1-471"><a href="#cb1-471" aria-hidden="true" tabindex="-1"></a>    \qquad \epsilon_{ij}\sim \operatorname{Normal}(0,\sigma^2).$$</span>
<span id="cb1-472"><a href="#cb1-472" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-473"><a href="#cb1-473" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Key idea"}</span>
<span id="cb1-474"><a href="#cb1-474" aria-hidden="true" tabindex="-1"></a>Practical workflow for an RBD analysis</span>
<span id="cb1-475"><a href="#cb1-475" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-476"><a href="#cb1-476" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>Plot the response by treatment and by block.</span>
<span id="cb1-477"><a href="#cb1-477" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-478"><a href="#cb1-478" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>Fit a model with treatment and block effects.</span>
<span id="cb1-479"><a href="#cb1-479" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-480"><a href="#cb1-480" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>Construct the ANOVA table.</span>
<span id="cb1-481"><a href="#cb1-481" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-482"><a href="#cb1-482" aria-hidden="true" tabindex="-1"></a><span class="ss">4.  </span>Test the treatment effect using $F=\mathrm{MST}/\mathrm{MSE}$.</span>
<span id="cb1-483"><a href="#cb1-483" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-484"><a href="#cb1-484" aria-hidden="true" tabindex="-1"></a><span class="ss">5.  </span>Interpret the treatment result after accounting for block variation.</span>
<span id="cb1-485"><a href="#cb1-485" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-486"><a href="#cb1-486" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-487"><a href="#cb1-487" aria-hidden="true" tabindex="-1"></a><span class="fu"># Practice Problems</span></span>
<span id="cb1-488"><a href="#cb1-488" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-489"><a href="#cb1-489" aria-hidden="true" tabindex="-1"></a>This section gives practice problems that reinforce one-way ANOVA and randomized block designs.</span>
<span id="cb1-490"><a href="#cb1-490" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-491"><a href="#cb1-491" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Practice problem"}</span>
<span id="cb1-492"><a href="#cb1-492" aria-hidden="true" tabindex="-1"></a>**Practice Problem 10** (One-way ANOVA from summary statistics). Suppose three groups have sample sizes $n_1=n_2=n_3=5$, sample means $$\bar{x}_1=10,</span>
<span id="cb1-493"><a href="#cb1-493" aria-hidden="true" tabindex="-1"></a>    \qquad</span>
<span id="cb1-494"><a href="#cb1-494" aria-hidden="true" tabindex="-1"></a>    \bar{x}_2=14,</span>
<span id="cb1-495"><a href="#cb1-495" aria-hidden="true" tabindex="-1"></a>    \qquad</span>
<span id="cb1-496"><a href="#cb1-496" aria-hidden="true" tabindex="-1"></a>    \bar{x}_3=18,$$ and sample variances $$s_1^2=4,</span>
<span id="cb1-497"><a href="#cb1-497" aria-hidden="true" tabindex="-1"></a>    \qquad</span>
<span id="cb1-498"><a href="#cb1-498" aria-hidden="true" tabindex="-1"></a>    s_2^2=5,</span>
<span id="cb1-499"><a href="#cb1-499" aria-hidden="true" tabindex="-1"></a>    \qquad</span>
<span id="cb1-500"><a href="#cb1-500" aria-hidden="true" tabindex="-1"></a>    s_3^2=6.$$ Compute the one-way ANOVA table and the observed F statistic.</span>
<span id="cb1-501"><a href="#cb1-501" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-502"><a href="#cb1-502" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-503"><a href="#cb1-503" aria-hidden="true" tabindex="-1"></a>::: {.callout-caution title="Solution"}</span>
<span id="cb1-504"><a href="#cb1-504" aria-hidden="true" tabindex="-1"></a>The total sample size is $N=15$ and $k=3$. The grand mean is $$\bar{x}_{\cdot\cdot}=\frac{5(10)+5(14)+5(18)}{15}=14.$$ The between-group sum of squares is $$\mathrm{SSB}=5(10-14)^2+5(14-14)^2+5(18-14)^2=160.$$ The within-group sum of squares is $$\mathrm{SSE}=(5-1)4+(5-1)5+(5-1)6=16+20+24=60.$$ Thus $$\mathrm{MSB}=\frac{160}{2}=80,</span>
<span id="cb1-505"><a href="#cb1-505" aria-hidden="true" tabindex="-1"></a>    \qquad</span>
<span id="cb1-506"><a href="#cb1-506" aria-hidden="true" tabindex="-1"></a>    \mathrm{MSE}=\frac{60}{12}=5.$$ The observed F statistic is $$F_{\mathrm{obs}}=\frac{80}{5}=16.$$ The ANOVA table is: $$\begin{array}{lcccc}</span>
<span id="cb1-507"><a href="#cb1-507" aria-hidden="true" tabindex="-1"></a>\hline</span>
<span id="cb1-508"><a href="#cb1-508" aria-hidden="true" tabindex="-1"></a>\text{Source} &amp; \text{SS} &amp; \mathrm{df}&amp; \text{MS} &amp; F <span class="sc">\\</span></span>
<span id="cb1-509"><a href="#cb1-509" aria-hidden="true" tabindex="-1"></a>\hline</span>
<span id="cb1-510"><a href="#cb1-510" aria-hidden="true" tabindex="-1"></a>\text{Between} &amp; 160 &amp; 2 &amp; 80 &amp; 16 <span class="sc">\\</span></span>
<span id="cb1-511"><a href="#cb1-511" aria-hidden="true" tabindex="-1"></a>\text{Within} &amp; 60 &amp; 12 &amp; 5 &amp; <span class="sc">\\</span></span>
<span id="cb1-512"><a href="#cb1-512" aria-hidden="true" tabindex="-1"></a>\text{Total} &amp; 220 &amp; 14 &amp; &amp; <span class="sc">\\</span></span>
<span id="cb1-513"><a href="#cb1-513" aria-hidden="true" tabindex="-1"></a>\hline</span>
<span id="cb1-514"><a href="#cb1-514" aria-hidden="true" tabindex="-1"></a>\end{array}$$</span>
<span id="cb1-515"><a href="#cb1-515" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-516"><a href="#cb1-516" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-517"><a href="#cb1-517" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Practice problem"}</span>
<span id="cb1-518"><a href="#cb1-518" aria-hidden="true" tabindex="-1"></a>**Practice Problem 11** (Why blocking can help). Explain why a randomized block design can have more power than a completely randomized one-way ANOVA design.</span>
<span id="cb1-519"><a href="#cb1-519" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-520"><a href="#cb1-520" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-521"><a href="#cb1-521" aria-hidden="true" tabindex="-1"></a>::: {.callout-caution title="Solution"}</span>
<span id="cb1-522"><a href="#cb1-522" aria-hidden="true" tabindex="-1"></a>A randomized block design separates nuisance variation due to blocks from random error. In a completely randomized design, block-to-block variation is absorbed into the error term. This can make $\mathrm{MSE}$ large and reduce the F statistic for treatment effects. In an RBD, block variation is removed through the block sum of squares, often making the residual error smaller. A smaller $\mathrm{MSE}$ makes it easier to detect genuine treatment differences.</span>
<span id="cb1-523"><a href="#cb1-523" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-524"><a href="#cb1-524" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-525"><a href="#cb1-525" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Practice problem"}</span>
<span id="cb1-526"><a href="#cb1-526" aria-hidden="true" tabindex="-1"></a>**Practice Problem 12** (RBD degrees of freedom). A randomized block design has $t=5$ treatments and $b=6$ blocks. Find the degrees of freedom for treatment, block, error, and total sources of variation.</span>
<span id="cb1-527"><a href="#cb1-527" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-528"><a href="#cb1-528" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-529"><a href="#cb1-529" aria-hidden="true" tabindex="-1"></a>::: {.callout-caution title="Solution"}</span>
<span id="cb1-530"><a href="#cb1-530" aria-hidden="true" tabindex="-1"></a>The degrees of freedom are: $$\mathrm{df}_{\mathrm{treatment}}=t-1=4,$$ $$\mathrm{df}_{\mathrm{block}}=b-1=5,$$ $$\mathrm{df}_{\mathrm{error}}=(t-1)(b-1)=4\cdot 5=20,$$ and $$\mathrm{df}_{\mathrm{total}}=tb-1=30-1=29.$$ They add correctly: $$4+5+20=29.$$</span>
<span id="cb1-531"><a href="#cb1-531" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-532"><a href="#cb1-532" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-533"><a href="#cb1-533" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Practice problem"}</span>
<span id="cb1-534"><a href="#cb1-534" aria-hidden="true" tabindex="-1"></a>**Practice Problem 13** (Treatment F statistic in an RBD). In a randomized block design with $t=4$ treatments and $b=5$ blocks, suppose $$\mathrm{SST}_{\mathrm{trt}}=90,</span>
<span id="cb1-535"><a href="#cb1-535" aria-hidden="true" tabindex="-1"></a>    \qquad</span>
<span id="cb1-536"><a href="#cb1-536" aria-hidden="true" tabindex="-1"></a>    \mathrm{SSE}=60.$$ Compute the treatment F statistic.</span>
<span id="cb1-537"><a href="#cb1-537" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-538"><a href="#cb1-538" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-539"><a href="#cb1-539" aria-hidden="true" tabindex="-1"></a>::: {.callout-caution title="Solution"}</span>
<span id="cb1-540"><a href="#cb1-540" aria-hidden="true" tabindex="-1"></a>The treatment degrees of freedom are $$t-1=3.$$ The error degrees of freedom are $$(t-1)(b-1)=3\cdot 4=12.$$ Therefore $$\mathrm{MST}=\frac{90}{3}=30,</span>
<span id="cb1-541"><a href="#cb1-541" aria-hidden="true" tabindex="-1"></a>    \qquad</span>
<span id="cb1-542"><a href="#cb1-542" aria-hidden="true" tabindex="-1"></a>    \mathrm{MSE}=\frac{60}{12}=5.$$ The treatment F statistic is $$F=\frac{\mathrm{MST}}{\mathrm{MSE}}=\frac{30}{5}=6.$$</span>
<span id="cb1-543"><a href="#cb1-543" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-544"><a href="#cb1-544" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-545"><a href="#cb1-545" aria-hidden="true" tabindex="-1"></a><span class="fu"># Summary</span></span>
<span id="cb1-546"><a href="#cb1-546" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-547"><a href="#cb1-547" aria-hidden="true" tabindex="-1"></a>This final section summarizes the key ideas from ANOVA applications and randomized block designs.</span>
<span id="cb1-548"><a href="#cb1-548" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-549"><a href="#cb1-549" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>One-way ANOVA compares $k$ group means using the ratio $F=\mathrm{MSB}/\mathrm{MSE}$.</span>
<span id="cb1-550"><a href="#cb1-550" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-551"><a href="#cb1-551" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The ANOVA F-test is a global test: it detects whether at least one group mean differs.</span>
<span id="cb1-552"><a href="#cb1-552" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-553"><a href="#cb1-553" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The sums of squares decomposition is $$\mathrm{SST}=\mathrm{SSB}+\mathrm{SSE}.$$</span>
<span id="cb1-554"><a href="#cb1-554" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-555"><a href="#cb1-555" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Multiple pairwise t-tests can inflate Type I error.</span>
<span id="cb1-556"><a href="#cb1-556" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-557"><a href="#cb1-557" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Good experimental design uses control, randomization, replication, and blocking.</span>
<span id="cb1-558"><a href="#cb1-558" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-559"><a href="#cb1-559" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Randomized block designs reduce nuisance variation by comparing treatments within homogeneous blocks.</span>
<span id="cb1-560"><a href="#cb1-560" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-561"><a href="#cb1-561" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>In an RBD, total variation is decomposed into treatment variation, block variation, and error variation.</span>
<span id="cb1-562"><a href="#cb1-562" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-563"><a href="#cb1-563" aria-hidden="true" tabindex="-1"></a><span class="fu">## References and Further Reading</span></span>
<span id="cb1-564"><a href="#cb1-564" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-565"><a href="#cb1-565" aria-hidden="true" tabindex="-1"></a>9 George Casella and Roger L. Berger, *Statistical Inference*, 2nd edition. Larry Wasserman, *All of Statistics*. ProbabilityCourse.com, online probability and statistics resources. Penn State STAT 415 online notes. Harvard Stat 110 online resources. E. Garcia-Portugues, *Notes for Predictive Modeling and Statistical Inference*.</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>MATH 5010 — Foundations of Statistical Theory &amp; Probability</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/wanghemath/Book-ProbabilityStatisticalTheory/edit/main/chapters/chapter-19-anova2-applications.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/wanghemath/Book-ProbabilityStatisticalTheory/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with Quarto</p>
</div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>